compliance/component.yaml, opencontrol.yaml
This replaces ATF-specific segments with "TODO"s so we can swing back and fill
them in once the project is in motion.
=> Update Compliance Masonry docs to remove ATF

.travis.yml, README.md
Changes the content of the README from ATF to OMB-specific. Removes Gemnasium temporarily as I am unable to configure the project due to our Github org breaking the Gemnasium site.
=> Change from ATF to OMB content

.gitignore, .travis.yml, Dockerfile, Procfile, README.md, devops/dev.sh, devops/dev_mode_install.sh, devops/prod.sh, devops/wait_for_db_then, docker-compose.yml, omb_eregs/settings_prod.py, reqs/management/commands/fetch_csv.py, requirements.in, requirements.txt, requirements_dev.txt, run.sh
This tries to standardize development using docker by using it to contain all of the Python and JS environment. The `docker-compose` command serves as the primary entry point to the app, with single-use "services" acting as commands. I don't think this is _too_ much of a pain (it's akin to running `bundle exec`) but I'd appreciate feedback. I can get the app running in one command on OSX (without Node/Python/Postgres configured), which is pretty awesome. Hypothetically, the same should apply on Windows.
=> Use Docker for local development (take 2)

omb_eregs/settings.py, requirements.in, requirements.txt, requirements_dev.txt
We'll want to replace this replace this with a more strict strategy once we
have a working API. In the mean time, open the flood gates to all.
=> Allow cross-origin API usage.

docker-compose.yml, manifest_dev.yml, manifest_prod.yml, omb_eregs/settings.py, omb_eregs/settings_prod.py
We'll be providing the DJANGO_SECRET_KEY via a cloud foundry user-provided
service, so mimic that in the Docker setup. Similarly, use the cloud.gov uris
variable instead of hard coding it into the settings file.
In the immediate, this resolves an issue in prod where a user'd be logged out roughly every other page view.
=> Use cloud.gov structure for host + secret key.

.eslintrc, README.md, devops/dev_ui.sh, devops/ui_build_run.sh, docker-compose.yml, manifest_dev.yml, manifest_prod.yml, package.json, ui/browser.js, ui/components/keywords.jsx, ui/components/requirements.jsx, ui/globals.js, ui/server.jsx
Dev mode for the UI (`docker-compose up dev`) will rebuild/restart the Node server. I wanted to get deeper into the hot module swapping, but hit my timebox.
This also connects the UI to the API (rather than calling out to the demo server); we'll need to merge this with the changes in #66. In that process, it should fix an issue where the database data was getting dropped on app shutdown.
There's a _little_ back tracking, but probably easiest to review changeset by changeset.
=> Add "dev" mode for UI; connect UI to local API

package.json, ui/components/requirements.jsx, ui/server.jsx, ui/styles.scss, webpack.config.js
This avoids the "webpack" way of combining style sheets with components in
favor of a separate CSS file. If we want to go the more modular route, we'll
need to figure out how to handle that CSS collection isomorphically.
=> Add simple stylesheet support.

omb_eregs/settings.py
While it's generally okay for an unrelated webpage to make AJAX requests
to our API, we _don't_ want that on the admin pages (due to the
"confused deputy" problem of a browser not knowing if AJAX requests were
intended by an end user).
This should resolve #49.
=> Restrict CORS around Django admin.

README.md, docker-compose.yml, reqs/tests/views_tests.py, reqs/views.py
Resolves #57. Also adds a `psql` command and fixes an issue where requirements could be repeated.
=> Sort requirements by number of matching keywords

docker-compose.yml, npm-shrinkwrap.json
Pin the exact versions of our libraries (and their dependencies). This is akin to `Gemfile.lock` file. `npm install` should use the data automatically.
Only potential caveat here: be sure to use `npm install --save` when adding new dependencies.
Also removes bound ports from a few of the service commands (to prevent port conflicts).
Should resolve #97
=> Use npm shrinkwrap

reqs/serializers.py, reqs/views.py, ui/components/index.jsx, ui/components/policies.jsx, ui/routes.jsx
Copy-paste then tweak the Keywords UI into a Policies UI, where the user can
see a list of all policies, and click through to the requirements contained in
that policy. There's a lot of overlap with the Keywords code, but I figure
we'll be replacing both soon, so I'm not too worried.
Should resolve #87.
=> Add minimal policy->req interface.

manifest_dev.yml, manifest_prod.yml
Lest they won't see the password config.
Both demo and prod environments are configured, so this will close #77.
=> Attach the config service to the UI servers.

reqs/tests/views_tests.py, reqs/views.py
This adds support for a `sort` parameter to the `/requirements/` endpoint.
@cmc333333 I wasn't able to make this play nicely with the code for sorting by number of matching keywords when using `OrderingFilter`, which is why this is custom code. It's possible I missed something. Hopefully the tests should still be useful even if I did.
=> Add ability to order requirements in API

reqs/management/commands/import_reqs.py, reqs/tests/import_reqs_tests.py
Keys are important /
Values, less. Sun breaks through cloud /
Green leaves soak it in.
Simple fix that means policy type will show up correctly in the admin view.
=> Make import use policy types keys, not values.

reqs/views.py, ui/__tests__/components/filter-list.test.jsx, ui/components/filter-list.jsx, ui/components/lookup-search.jsx, ui/components/requirements.jsx, ui/routes.jsx
This generalizes the FilterList/Filters to remove ties to keywords, then configures a new set to work with policy titles. This does **not** need to be reviewed before today's demo.
Looks like:
=> Add a policy search widget

ui/__tests__/components/requirements/by-policy.test.jsx, ui/__tests__/components/requirements/tabs.test.jsx, ui/components/requirements/by-keyword.jsx, ui/components/requirements/by-policy.jsx, ui/components/requirements/container.jsx, ui/components/requirements/requirement.jsx, ui/components/requirements/tabs.jsx, ui/routes.jsx
Building on #149, this splits up the Requirements component into:
* Container (which includes the left-side filters)
* Tabs
* ByKeyword
* ByPolicy
Requirements always include the Container and Tabs, but then, depending on path, include either ByKeyword or ByPolicy.
Looks like:
Should resolve #123
=> Add by-policy tab

omb_eregs/settings.py, reqs/admin.py, reqs/models.py
Three quick wins that OMB's requested:
* Remove taggit's Tag model from the admin
* Add a search box for filtering models. Super naive approach, but this works
* Add OMB policy id to policy names
=> Tweaks to admin

devops/dev_api.sh, devops/prod_api.sh, omb_eregs/settings.py, reqs/admin.py, reqs/tests/admin_tests.py, requirements.in, requirements.txt, requirements_dev.txt
That which was before /
Can be again, but the rain /
Never falls upwards.
Add tracking of version history for changes made to objects in the admin view, with the ability to both see the history of a given object and revert to prior states.
=> Add django-reversion to admin view, and a basic test for it.

.travis.yml, README.md, devops/deploy.sh
Use [autopilot](https://github.com/contraband/autopilot) to limit downtime while deploying. The login information is now set in the Travis UI rather than the .travis.yml. Also adds instructions for how to deploy. 
I've tested the deploy script, but will have to wait until this is merged to verify the Travis side.
Should resolve #163
=> Blue Green deploys

ui/assets/css/_requirements.scss, ui/components/requirements/requirement.jsx
For each requirement, the list of associated keywords is shown. This does not link the keywords. 
@cmc333333, I'd like to work together on linking them if you have time. My best thinking involves fetching the `keywords` endpoint and comparing strings to get the appropriate ID. I wonder if there's not a more elegant solution, given that this information is already in the app.
=> Adds keywords to requirements

package.json, ui/__tests__/components/filter-list.test.jsx, ui/__tests__/components/pagers.test.jsx, ui/__tests__/components/requirements/tabs.test.jsx, ui/__tests__/components/search-autocomplete.test.jsx, ui/__tests__/util/mockRouter.js, ui/components/filter-list.jsx, ui/components/pagers.jsx, ui/components/requirements/by-policy.jsx, ui/components/requirements/container.jsx, ui/components/requirements/tabs.jsx, ui/components/search-autocomplete.jsx
Part of #170, this makes testing a bit more difficult, but means we don't have to thread the router through the whole app, which is particularly important as we create more and more nested components.
=> Use the router in `context` rather than passing it around

package.json
Cloud Foundry buildpacks might drop support for a minor version; 6.x is the
LTS.
=> Don't specify node minor version.

README.md, docker-compose.yml, manifest_dev.yml, manifest_prod.yml, omb_eregs/max_backend.py, omb_eregs/settings.py, omb_eregs/templates/403.html, omb_eregs/tests/max_login_tests.py, omb_eregs/urls.py, requirements.in, requirements.txt, requirements_dev.txt, setup.cfg
Connects to MAX for login needs. For the most part the django-cas-ng library does what we need; the exception is that MAX usernames are meaningless, so we override that bit to treat the email address as a username.
To emphasize, this strategy requires that we create user accounts _ahead_ of their first login; we're using MAX for authentication not authorization. I've create user accounts on the demo server for everyone on the 18F side.
This requires a `docker-compose build` if running Python tests; shouldn't need it otherwise. Should resolve #130
=> Use MAX Login on cloud.gov

requirements.txt, requirements_dev.txt
Seven is better /
Than five. Except when counting /
Loud seagulls nearby.
Update Django from 1.10.5 to 1.10.7 (which appears to bring with it some other dependency updates.)
=> Update Django to 1.10.7

omb_eregs/settings.py, reqs/serializers.py, requirements.in, requirements.txt, requirements_dev.txt, ui/components/requirements/requirement.jsx
This is needed for #181 (so we know which keyword id was clicked)
=> Include keyword ids in nested models of Requirements API

npm-shrinkwrap.json, package.json, ui/server.js, webpack.config.js
Tested against IE10 (which does not have `Object.assign`, for example). This
should only affect the browser-visible JS.
Resolves #197
=> Add babel-polyfill to backport new JS functions.

ui/__tests__/components/requirements/metadata.test.jsx, ui/assets/css/_requirements.scss, ui/components/requirements/requirement.jsx
More information, /
More properties, more info. /
Surely thus better.
Adds:
- Issuing body
- Policy title
- Policy issuance date
- OMB Policy ID
Also displays “Sunset date: none” if there's no sunset date.
Other than OMB Policy ID, these are all arbitrary additions, and not my idea of what the essential properties are.
=> Display more metadata with requirements

ui/components/requirements/requirement.jsx
Per @nicoleslaw 's suggestion.
Order is now:
- Impacted entity (“applies to”).
- Issuing body.
- Policy title.
- OMB policy ID.
- Issuance date.
- Sunset date.
- Topics.
=> Change display order of properties of requirements

devops/integration_tests/smoke_tests.py, docker-compose.yml, omb_eregs/settings.py, ui/server-render.js
This resolves two issues ZAP found:
* using a large page number gives a 404 from the API, but had been 500ing the UI
* cookies should only be sent over SSL (when SSL is available)
~~I think it makes the most sense to write an integration test once #208's merged.~~
=> Pass API 404's to the user.

ui/components/dap.jsx, ui/components/errors/fiveHundred.jsx, ui/components/errors/fourHundred.jsx, ui/components/errors/fourOhFour.jsx, ui/components/html.jsx, ui/routes.jsx
We need to explicitly trigger a pageview when the user loads another page,
too.
This doesn't attempt to resolve the link usage drama mentioned here:
https://github.com/digital-analytics-program/gov-wide-code/pull/47 but should
be enough to get us started.
=> Include DAP for page tracking.

npm-shrinkwrap.json, package.json, ui/__tests__/api.test.js, ui/api.js, ui/config.js
A short-term solution for #231, this sets up a per-endpoint
least-recently-used cache to prevent repeated API calls from being made.
=> Add an API cache to the frontend.

omb_eregs/settings.py, ui/do-not-cache.js, ui/server.js
Without setting explicit headers, CloudFront has a cache timeout of 24 hours. This sets that timeout to zero (which is what we assumed) for the time being. It should resolve #264.
=> Request users not to cache content

omb_eregs/settings.py, ui/do-not-cache.js, ui/server.js
We need these cache headers in production before the next release.
=> Hotfix #265

ereqs_admin/apps.py, ereqs_admin/tests/apps_tests.py, omb_eregs/settings.py, reqs/models.py
As users make changes in the admin screen, Django generates minimal logs which are then stored in the database. This also logs those changes to the console. Additionally, Django's admin doesn't do a great job of tracking how many-to-many fields change (which is problematic as both permissions and groups are many-to-many), so this also specifically logs those.
Should resolve #219
=> Log changes to console

ereqs_admin/admin.py, ereqs_admin/forms.py, ereqs_admin/templates/admin/auth/user/add_form.html, ereqs_admin/tests/admin_tests.py, ereqs_admin/tests/both_user_forms_urls.py, omb_eregs/settings.py
Adds new forms to account for an environment where passwords aren't used. These forms should only be active when there's a configured MAX_URL (so, to test locally, you'll need to uncomment that environment variable from the docker-compose file).
Should close #252
=> Remove password from MAX authenticated users

omb_eregs/settings.py, requirements_dev.in, requirements_dev.txt
Pympler causes 500s in some situations around multiple requests (thanks for
finding this issue, @tadhg-ohiggins!). We only used it to provide a panel in
the debug toolbar, so let's just axe it.
=> Remove pympler.

reqs/tests/admin_tests.py, requirements.txt, requirements_dev.txt
We updated to Django 1.11 this past sprint, which introduced an
incompatibility with django-autocomplete-light. Annoyingly, when going to the
edit screen, existing topics were not populated (though they were saved
correctly.)
This should resolve #285
=> Fix issue around preloading topics.

newrelic.js
By default, New Relic will treat a 401 as an error (hence affecting downtime
alerts, etc.). 401's do not indicate an error state for us, so we should
ignore them the same way 404s are.
Should resolve #274 
Tested on demo -- appears to continue to log hits while not registering errors on 401s
=> Configure New Relic to ignore 401s.

reqs/models.py, reqs/serializers.py, reqs/tests/model_tests.py, ui/components/policies/policy-view.jsx
Per #251, we'd like to include a policy number (where available) in the UI.
Rather than calculate it there, this just adds a computed field to the API
which includes the information.
It then uses this field when displaying the policy titles in the policies tab.
=> Add a "title_with_number" policy attribute.

manifest_dev.yml, manifest_prod.yml
The UI instances are rather minimal -- not only does Node have a light
footprint (hovering around 50M usage), most users will only hit the service
once on initial page load. As a result, it looks like we can spin up several
more UI servers to handle request volume by dropping their memory consumption.
=> Up the number of UI services we're running.

ui/components/filters/autocompleter.js
This makes the autocompleter tab-accessible.
This is part (perhaps all?) of #292
=> Add a tabIndex to the react-select autocompleter.

reqs/models.py, reqs/templates/admin/reqs/policy/change_form.html
We had been making one query per requirement on the policies edit page (to
gather the topics names). We can prefetch all of those topics in a single
query instead, though it requires a few hoops.
This cuts load time of one of the pages from about 30 seconds to 6 for me (in
dev mode), so, still not fast, but much better.
=> Reduce number of queries in the policies edit page.

ui/assets/css/_policies.scss, ui/components/policies/policy-view.jsx
Makes things look neater. I made the size of the font in "99+" circles smaller to unwonkify the display.
=> Show 99+ when there are 100 or more relevant requirements

README.md
Warn local users /
About Minio upload. /
Help guests find the host.
=> Add readme section about hosts file and Minio for local development.

README.md, devops/integration-compose.yml, devops/integration-tests.sh, devops/integration_tests/conftest.py, docker-compose.yml
We'd like to use a `localhost` URL when presenting uploaded files to end users
(so they can access those files outside of Docker). ~~To do this, we'll attach
the APIs to the minio network stack. This conflicts with exposing ports
directly, however, so we need *minio* to expose those ports.~~
To do this, we'll create a "proxy" container which exists solely for other containers to join its network stack. This will allow apps to talk to each other via `localhost` just as the end user will.
@tadhg-ohiggins what do you think of this approach?
=> Create shared, "proxy" network in docker

docker-compose.yml, manifest_dev.yml, manifest_prod.yml, omb_eregs/settings.py, ui/components/html.jsx, ui/config.js
We had two different URLs to account for communications within the docker
network and between the browser and API. Since #345 puts all of that network
into one proxy component, we can collapse into a single configuration option.
=> Remove separate private/public API urls.

ui/components/html.jsx
The Python client does this automatically, but the Node client does not.
Ironically, we probably want statistics around the Node app's browser more
than anything. Activate it here (it degrades to an empty string when newrelic
is not enabled).
=> Insert newrelic browser logging.

reqs/admin.py, reqs/tests/admin_tests.py
For agencies, we import a bunch of data from itdashboard.gov, so we'll
separate out readonly from editable fields.
For agency groups, we make the "agencies" field a horizontal filter so that
it's a bit more manageable.
Builds off #347 
Should resolve #339 
Looks like:
=> Add agencies, groups to admin UI.

reqs/admin.py, reqs/tests/admin_tests.py
As agencies are populated via an import script, we should remove the ability
for admins to create new instances.
=> Remove add permission for agencies.

omb_eregs/settings.py, reqs/models.py, reqs/serializers.py, reqs/tests/views_simple_tests.py, reqs/views/policies.py, reqs/views/requirements.py, reqs/views/simple.py, ui/__tests__/components/filters/existing-container.test.js, ui/__tests__/components/lookup-search.test.jsx, ui/__tests__/components/policies/container.test.js, ui/__tests__/components/requirements/container.test.js, ui/api.js, ui/components/filters/autocompleter.js, ui/components/filters/existing-container.js, ui/components/lookup-search.jsx, ui/components/policies/container.js, ui/components/requirements/container.js, ui/routes.jsx
Builds on #351 ([diff](https://github.com/18F/omb-eregs/compare/340-agency-api...341-agency-filter-ui)) to add a UI element for searching by agency. To do this, query by a common `search` parameter over the API and re-using much of the existing filters code.
Should resolve #341
=> Agency Filter UI

ui/__tests__/components/policies/container.test.js, ui/__tests__/components/requirements/container.test.js, ui/components/policies/container.js, ui/components/requirements/container.js
As we don't have data yet, temporarily hide these inputs from the user-facing
UI.
=> Comment out Agency UI.

reqs/models.py
Django models should always have a __str__; otherwise, when the model is in a
select field, it'll just say, e.g. "Agency Object".
Compare:
=> Add the office name to the Django admin.

ui/__tests__/components/ajax-loading.test.jsx, ui/assets/css/_loading-indicator.scss, ui/assets/css/main.scss, ui/components/ajax-loading.js, ui/components/filters/existing-container.js, ui/components/homepage/new-policies/container.js, ui/components/lookup-search.jsx, ui/components/policies/container.js, ui/components/requirements/container.js, ui/components/spinner.jsx
React-resolver doesn't quite give us the tools needed to implement a loading-spinner during AJAX requests, but we can extend their [Resolver](https://github.com/ericclemmons/react-resolver/blob/master/src/Resolver.js) to get there.
Looks like
Should resolve #373
=> Add a spinner during AJAX load

README.md, devops/run_api.sh, reqs/management/commands/import_reqs.py, reqs/management/commands/sync_agencies.py, reqs/tests/import_reqs_tests.py, reqs/tests/sync_agencies_tests.py
This is step 2 of fixes around #374; it creates versions when importing/synchronizing Policies, Requirements, Topics, Agencies, and AgencyGroups.
This PR also includes a somewhat unrelated test refactor which converts some test data into a factory method -- I ended up not needing this, but figured it wouldn't hurt to keep.
=> Create versions in import/sync scripts

ereqs_admin/revision_admin.py, ereqs_admin/tests/revision_admin_tests.py, reqs/admin.py
When users save models, a copy of all the model's fields is stored in a
version history. As the database schema changes, that version becomes less
compatible. We can warn the user when this occurs, though, by comparing the
fields that would serialize now to the fields stored in the database.
There's a nasty snag where the serialized field names don't quite match up
when comparing the names on an unsaved Django model. This works around that by
grabbing a model from the database and showing a slightly different warning
when that's not possible.
Pretty easy to change the message text if we don't like this version.
=> Extend VersionAdmin with schema mismatch warnings.

ui/__tests__/components/requirements/requirements.test.jsx, ui/components/requirements/requirement.jsx
Per a request from OMB, we want to temporarily hide impacted entity meta data
when it is one of a handful of values. OMB wants to keep the information for
manual cleanup and analysis.
This also removes the default ("unknown") as it was part of the requested
blacklist.
@tadhg-ohiggins what do you think about this? It's pretty straight forward and achieves the requested ends. I'm not keen on the precedent, but not terribly opinionated.
=> Add a blacklist of "masked" impacted entities.

.travis.yml
The new build images on Travis include a current-enough version of Docker and
don't include `docker-engine` in their app repos.
=> Remove Docker update from CI.

ui/__tests__/components/search/search.test.js, ui/components/search/search.jsx
As we want to keep the user on the same page/with the same filters when they
search, we create hidden input values to match their current query. We weren't
deleting the _existing_ search parameter when viewing policies (though we were
if viewing requirements).
Should resolve #384
=> Remove the current search field from inputs.

ui/__tests__/components/lookup-search.test.jsx, ui/components/lookup-search.jsx, ui/server.js
To resolve #412, this
1. Fixes error handlers (to test, try raising an error in one of the components)
2. Allows non-JS topic search to be empty
=> Fix bug around error pages, allow empty search

ui/__tests__/components/filters/fallback-view.test.js, ui/__tests__/components/filters/selector.test.js, ui/assets/css/_req-filter-ui.scss, ui/assets/css/_search-autocomplete.scss, ui/components/filters/fallback-view.jsx, ui/components/filters/list-view.jsx, ui/components/filters/selector.js, ui/components/homepage/topic-autocomplete.js, ui/components/homepage/view.jsx, ui/components/pagers.jsx, ui/components/policies/container.js, ui/components/policies/policy-view.jsx, ui/components/requirements/container.js, ui/components/search/search.jsx
Partial solution to #308:
* Tie labels to input elements via aria-label/labelledby
* Add contrast to autocomplete element, some unseen links
* Swap a css image and an image input w/ a button+img
* Add aria-labels for uninformative links.
This doesn't solve:
* [Severe] Elements with ARIA roles must ensure required owned elements are present (1)
* I'm trying to get a sense from #g-accessibility whether or not this is actually significant --[an "accessible" autocomplete](https://haltersweb.github.io/Accessibility/autocomplete.html) has the same error.
* [Warning] The web page should have a title that describes topic or purpose (1)
* This will be resolved w/ #407 (nice)
* [Warning] These elements are focusable but either invisible or obscured by another element (1)
* I think this is a false …
=> Accessibility tweaks

ui/__tests__/components/thing-counters.test.jsx, ui/components/policies/policies-view.jsx, ui/components/thing-counters.jsx
Sometimes when we search /
We only think we're looking /
For the correct things.
Correct capitalization, add more rigor about detecting unfiltered queries.
=> Capitalization and unfiltered results language corrections

ui/components/thing-counters.jsx
Always push your code /
Right before the team demo /
(No `values` support).
Accommodate an older Node version than I thought we were using.
=> Fix Node version error around Object.values

ui/components/lookup-search.jsx, ui/redirects.js
Our nightly build/deploy is failing due to a linting error. npm's `shrinkwrap` doesn't capture the dev environment; I'm 90% positive that the airbnb style guide moved a bit from under us and didn't keep follow semantic versioning, but I didn't look too hard.
In any event, this should fix.
=> Switch comment style, per airbnb guide.

ui/__tests__/components/disclaimer.test.js, ui/assets/css/_footer.scss, ui/assets/css/_header.scss, ui/components/disclaimer.jsx, ui/components/footer.jsx, ui/components/homepage/view.jsx, ui/components/navbar.jsx
This builds off @micahtaylor's work to add a beta dropdown in the header, a footer, and updated disclaimer text on the home page. I believe these are the necessary changes for launch (sans removing password).
=> Add header/footer/disclaimer

.circleci/config.yml, .travis.yml, devops/circle-deploy.sh, devops/deploy.sh, devops/integration-compose.yml, devops/transform_circle.py, docker-compose.yml, package.json, runtime.txt
In this first step, we run all of our tests in CircleCI and begin deploying with it. Most of the code is copied from the Travis file or atf-eregs.
We need to get a nightly build running (#455) before we can turn off Travis entirely.
=> Start CircleCI conversion

ui/components/search/search.jsx
When a user is on a non-policies/requirements page (the home page,
search-redirect pages, the privacy page), the header search bar needs to
redirect the user to the "requirements" page. Unfortunately, we were using a
relative url, which meant deeply nested pages (search-redirects) would
redirect to, e.g.  `/search-redirect/topics/requirements/` rather than
`/requirements/`.
This resolves by using a root-relative url.
=> Use root-relative url for search when unsure.

.circleci/config.yml
Code Climate's coverage reporter will fail if submitting coverage for the same
commit twice. We'll be doing that relatively frequently, however, in both our
nightly builds and if we ever want to restart a failed deploy.
This resolves by allowing the upload step to fail.
For verification, compare the "Submit Coverage" steps in
https://circleci.com/gh/18F/omb-eregs/70 and https://circleci.com/gh/18F/omb-eregs/71
=> Allow Circle builds to be restarted.

ui/__tests__/components/lookup-search.test.jsx, ui/components/lookup-search.jsx
If a user doesn't have JavaScript enabled (or acts before the autocompleteres
are finished loading), they will get to the LookupSearch page. This changeset
improves that page's interface by adding some more whitespace and indicating
when no search results are found.
Should resolve #434 
Looks like:
=> Improve styles, text on lookup search page.

npm-shrinkwrap.json, package.json
We had moved source-map-support out of the production libs because it was only
referenced in webpack. Unfortunately, that reference actually inserts a
_string_ into the resulting file, which imports source-map-support, meaning it
_is_ needed for production.
This will fix broken deploys (locally, we have the dev dependencies
installed).
=> Move source-map-support back to a production lib.

ui/__tests__/server-render.test.js, ui/assets/css/_base.scss, ui/assets/css/_button-like.scss, ui/assets/css/_homepage.scss, ui/assets/css/_policies.scss, ui/assets/css/_print.css, ui/assets/css/_req-filter-ui.scss, ui/assets/css/_stars-divider.scss, ui/assets/css/main.scss, ui/assets/css/utils/_landing.scss, ui/assets/img/star.svg, ui/components/errors/fourOhFour.jsx, ui/components/homepage/view.jsx, ui/components/html.jsx, ui/server-render.js
This updates the design of the 404 page. Unfortunately, our existing strategy around accessing the current url (which relies on react-router) doesn't work well for 404 pages. To accommodate, this effectively mocks that extra context out. That isn't a great long term strategy, but I suspect a longer term strategy will be worked out when refactoring for Next.js
It also adds a star-based divider to the homepage (per the latest designs) and extracts some of those styles for use on the 404 page.
=> 404 page and homepage stars

api/ereqs_admin/management/commands/cf_migrate.py, api/run_api.sh
We run multiple `api` servers in production, but we only want one of them to
be responsible for migrating our database (lest one instance's migration will
prevent the other from starting). This changeset adds a management command
which migrates the database only on the first instance when on cloud.gov, and
every time when not (e.g. local development).
Should resolve #422
=> Prevent multiple migrations in prod.

ui/components/filters/existing-container.js
Resolves #493 by adding the policy number to policy-based filters.
Here's how things look with and without a policy number:
=> Use policy number when displaying policy filter.

docker-compose.yml
Docker for Mac can be very slow when performing file access on a shared
directory due to consistency guarantees. This tweaks our mounted directories
so that there can be a slight delay between synchronization as the benefit of
much faster reads.
This appears to be a solution to #258 in my experience, dropping local admin
load time dropping to roughly what we see in production.
We had tried this solution before, but support wasn't fully baked.
=> Loosen consistency guarantees in Docker.

.circleci/config.yml, .gitignore, ui/package.json
To make it easier to do testing, I added a `test:watch` command to `package.json` so that the tests will run whenever a file changes. This can be run inside of the docker container with:
`docker-compose run --rm npm run test:watch`
I had to change some of the jest configuration to get it to run in the docker container (for some reason the tests would _not_ be re-run if the coverage option was supplied) but I think I replicated all of the functionality by moving it into CLI arguments.
=> Add test:watch command for front end in package.json

ui/__tests__/components/search/search.test.js, ui/components/search/search.js
If the Javascript is executed on the client, then we should intercept the form's submit event and do a client side re-routing. If the JS isn't executed, use the form action.
Closes #506
=> Handle navbar search clientside if possible

ui/__tests__/components/error.test.js, ui/__tests__/components/errors/four-oh-four-error.test.js, ui/__tests__/components/errors/unexpected-error.test.js, ui/__tests__/components/errors/user-error.test.js, ui/__tests__/components/filters/existing-container.test.js, ui/__tests__/components/filters/remove-link-container.test.js, ui/__tests__/components/filters/remove-search-container.test.js, ui/__tests__/components/requirements/metadata.test.js, ui/__tests__/components/requirements/policy-link.test.js, ui/components/error.js, ui/components/errors/four-oh-four-error.js, ui/components/errors/unexpected-error.js, ui/components/errors/user-error.js, ui/components/filters/existing-container.js, ui/components/filters/remove-link-container.js, ui/components/filters/remove-search-container.js, ui/components/filters/remove-view.js, ui/components/requirements/metadata.js, ui/components/requirements/policy-link.js, ui/components/requirements/requirement.js, ui/components/requirements/topic-link.js
Restructured some of the component files to only have on component in each file. This enables a few things:
1. It is easier to take inventory of all of our component and component names to ensure they are consistent
2. It is easier to know where to find a given component
3. It helps determine what can be DRYed up and refactored
Along the way, I also converted use of `React.createElement()` to JSX where I can ran into it.
Part of #504
=> One component per file

api/document/models.py, api/document/serializers.py, api/document/tests/serializers_test.py, api/document/tests/views_test.py, api/document/urls.py, api/document/views.py, api/omb_eregs/urls.py
This endpoint allows us to grab either the root of a document or some subsection. It doesn't make any attempt at paging just yet, but should be enough to help us prototype viewing documents.
=> Add endpoint for serializing trees

ui/components/policies/policies-view.js
This is a short-term fix for a typo'd route name. For a longer-term solution,
we should use our prop-type checking to validate the route.
=> Fix route typo.

ui/__tests__/components/app-wrapper.test.js, ui/__tests__/util/api/queries.test.js, ui/components/app-wrapper.js, ui/util/api/queries.js
If requesting a policy detail page for a policy which doesn't exist, we should return a 404 rather than a 500.
Resolves #557
=> Account for bad policy id

ui/__tests__/components/search/search.test.js, ui/components/search/search.js
The Search component was written prior to our Next.js-based routes, which
meant that it was doing all of its logic via substring searches. This
refactors it to instead define a constant for the default route and a mapping
between routes and their parameter names.
In the process, it alters the logic to only keep the query params when the
user is on one of the two whitelisted pages (requirements or policies); query
parameters on other pages aren't relevant.
Should resolve #558
=> Rework Search component to be route-based.

ui/__tests__/components/homepage/new-policy-view.test.js, ui/__tests__/components/policy/req.test.js, ui/__tests__/components/requirements/topic-link.test.js, ui/components/homepage/new-policy-view.js, ui/components/policy/req.js, ui/components/requirements/policy-link.js, ui/components/requirements/requirement.js, ui/components/requirements/requirements-view.js, ui/components/requirements/topic-link.js
https://github.com/18F/omb-eregs/issues/549
Move the `MetaData` components found in the requirements page over into the `Policy` page.
=> Add the metadata on the policy page

ui/__tests__/pages/policies.test.js, ui/__tests__/pages/requirements.test.js, ui/components/search-filter-view.js, ui/pages/policies.js, ui/pages/requirements.js
Per feedback from @carodew, the partial navigation tabs on the policies
results page were confusing and no longer provided use. This removes them by
moving their markup into the requirements listing page.
It also removes the RequirementsTab component as that is no longer in use.
=> Remove the navigation tabs from policies results.

README.md, api/document/management/commands/import_xml_doc.py, api/document/models.py, api/document/tests/import_xml_doc_test.py, api/document/tests/models_test.py, api/example_docs/m_16_19_1.xml, api/requirements.in, api/requirements.txt, api/requirements_dev.txt
While we begin thinking through what an import/authoring tool would look like,
we have pressing needs to display whole documents. This command acts as a
stop-gap, giving an interface for entering these documents (as XML).
This also includes some XML to represent M-16-19. It doesn't account for inline elements (like footnote citations) at all, but should make generating documents a bit easier.
=> Script to import a document from XML

ui/__tests__/components/nodeRenderers/fallback.test.js, ui/__tests__/components/nodeRenderers/heading.test.js, ui/__tests__/components/nodeRenderers/para.test.js, ui/__tests__/components/nodeRenderers/policy.test.js, ui/__tests__/components/nodeRenderers/sec.test.js, ui/__tests__/pages/document.test.js, ui/__tests__/util/api/queries.test.js, ui/components/nodeRenderers/fallback.js, ui/components/nodeRenderers/heading.js, ui/components/nodeRenderers/para.js, ui/components/nodeRenderers/policy.js, ui/components/nodeRenderers/sec.js, ui/pages/document.js, ui/routes.js, ui/util/api/endpoints.js, ui/util/api/queries.js
Includes renderers for:
* paragraphs
* headings
* sections
along with some minimal, inline styles to distinguish them. The goal in pushing this up is that we'll have a common base to start dividing up work.
=> Initial document-viewing page

ui/__tests__/components/filters/selector.test.js, ui/components/filters/selector.js
We moved the redirectQuery function around during our last sprint; looks like
we missed a reference.
=> Fix import error.

ui/__tests__/components/filters/selector.test.js, ui/components/filters/selector.js
We moved the redirectQuery function around during our last sprint; looks like
we missed a reference.
---
This cherry-picks the one commit from #577 into the release branch.
=> Fix import error. (Hotfix)

docker-compose.yml
The current Docker setup is almost perfect out-of-the-box for Windows, with the exception that it uses the `PWD` environment variable, which doesn't exist on Windows shells like `cmd.exe`.  So this just swaps out the variable for `.`, which I believe works just as well.
=> Add Windows support for Docker

docker-compose.yml
This is a follow-up to #592 that fixes a problem on Windows where 0.0.0.0 isn't a valid IP address on Windows browsers (Edge, Chrome, and Firefox all report it as an invalid address).  So this changes `API_URL` to use `localhost` instead, so the front-end's XHR calls on Windows browsers work.
=> Fix value of API_URL in docker-compose.yml to work on Windows.

api/document/tests/xml_importer/preprocess_test.py, api/document/xml_importer/importer.py, api/document/xml_importer/preprocess.py
We (currently) have two sources of metadata for a document: the document
itself and a Policy object in the database. Unfortunately, this allows for the
same data to be stored in two places (and potentially conflict). We should at
least warn the user when we see this happening.
=> Warn about mismatching data when importing XML.

api/document/serializers.py, api/document/tests/serializers_test.py, api/document/tests/views_test.py, api/document/urls.py, api/document/views.py, api/reqs/tests/views_policies_tests.py, api/reqs/views/policies.py
This re-uses the policy-id-or-m-number logic @rememberlenny wrote to do the same for whole documents. It also adds policy details to the root of the serialized tree.
=> Allow documents to be queried by M-number, add policy meta data

ui/__tests__/components/node-renderers/footnote.test.js, ui/components/node-renderers/footnote.js, ui/css/main.scss, ui/css/module/_footnotes.scss, ui/pages/document.js
We won't be able to get the footnotes at the bottom of the page prior to demo.
In its stead, render a display that's at least evocative of the original
design.
Looks like
=> Add temporary, simple footnote style.

ui/routes.js
The API now allows documents to be looked up by their policy's M-number (and
soon, slug); allow that on the frontend as well.
This pulls out the only part of #606 that feels essential for demo
=> Allow use of non-ints when looking up documents.

api/document/serializers.py, api/document/tests/serializers_test.py, ui/__tests__/components/labeled-text.test.js, ui/__tests__/components/node-renderers/from.test.js, ui/__tests__/components/node-renderers/policy.test.js, ui/__tests__/test-utils/node-renderers.js, ui/__tests__/util/api/queries.test.js, ui/__tests__/util/document-node.test.js, ui/__tests__/util/render-node.test.js, ui/components/labeled-text.js, ui/components/node-renderers/from.js, ui/components/node-renderers/noop.js, ui/components/node-renderers/policy.js, ui/util/api/queries.js, ui/util/document-node.js, ui/util/render-node.js
Serving as a first step of the solution for #597, this adds a set of metadata fields to the top of a policy and hides the document's "preamble" (if present). This isn't well styled, but should be semantically okay. Easiest to review changeset-by-changeset
Along the way, it also:
* Allows a url like `/document/M-16-19`
* Fixes the pdf url from the document API
* Unstyles `sec` nodes
Looks like
=> Initial preamble display

api/document/tests/serializers_test.py, api/document/tests/tree_test.py, api/document/tests/views_test.py, api/document/tests/xml_importer/annotations_test.py, api/document/tree.py
This resolves a minor annoyance around creating document trees. All nodes
within a single document should be associated with the same policy, yet we
needed to specify the policy for every node that we added.
This removes the redundancy by adding the policy as an attribute of the
underlying graph and using that whenever adding a new child node. It's still
possible to manually set the policy differently in a child (though I don't see
a use case).
=> Remove the need to repeat policy in tree children.

api/document/serializers.py, api/document/tests/serializers_test.py, api/document/tests/views_test.py, api/document/views.py, ui/__tests__/components/node-renderers/policy.test.js, ui/__tests__/util/api/queries.test.js, ui/components/node-renderers/footnote.js, ui/components/node-renderers/policy.js, ui/css/module/_footnotes.scss, ui/util/api/queries.js, ui/util/render-node.js
This modifies the API to include footnotes in the `meta` data for the root of a document and any `table`s. It then uses that new data to display footnotes at the bottom of the `Policy` component. This should resolve a majority of #624, though we'll want a design review before closing.
(note that footnotes aren't displaying inline anymore)
---
---
=> Display footnotes at bottom of page

api/document/serializers.py, api/document/tests/serializers_test.py
This leverages DRF's serialization framework to separate out the logic
necessary to generate the "meta" field from the DocCursor. This should make it
easier to test and allow us to focus future changes.
=> Rework "meta" field serialization.

api/document/models.py, api/document/serializers.py, api/document/tests/serializers_test.py, api/document/tests/views_test.py, ui/__tests__/components/content-renderers/footnote-citation.test.js, ui/__tests__/util/render-node.test.js, ui/components/content-renderers/footnote-citation.js
This extends the FootnoteCitation serialization to include the referenced node, which should make it easier to display (and lines up well with #629).
I hope @tadhg-ohiggins will enjoy the use of `singledispatch` over `abc`.
=> Include footnote content in citation annotation

ui/components/content-renderers/footnote-citation.js
The `render-node` module exports `renderNode` by default.
=> Fix renderContent import.

api/document/tests/serializers_test.py, api/document/tests/tree_test.py, api/document/tests/utils.py, api/document/tests/views_test.py, api/document/tests/xml_importer/annotations_test.py, api/document/tree.py, api/document/xml_importer/importer.py
90% of the time when we re-number nodes in our document tree (to agree with
the nested-set model), we want to create them immediately afterwards. The
removes a chunk of redundancy by having the renumber method also save the
DocNodes.
=> Refactor redundant node saves.

ui/components/node-renderers/math.js
It turns out we want `displayMode` to be `true`. Thanks @cmc333333 for helping find this!
=> Quick fix for katex.js rendering issues.

README.md, docker-compose.yml, ui/next.config.js, ui/webpack.config.js
Some docker setups, such as Windows, don't notify processes of changes to the filesystem like Linux does, so we need to use polling.
This detects if `USE_POLLING` is set in the host environment, and if so, configures webpack's dev middleware to use it (both in next.js and the CSS webpack process).
To do:
=> Enable webpack dev middleware polling if USE_POLLING is set.

ui/__tests__/components/node-renderers/policy.test.js, ui/__tests__/components/node-renderers/table/tfoot.test.js, ui/__tests__/pages/document.test.js, ui/__tests__/test-utils/node-renderers.js, ui/__tests__/util/document-node.test.js, ui/components/node-renderers/policy.js, ui/components/node-renderers/table/index.js, ui/components/node-renderers/table/tfoot.js, ui/pages/document.js, ui/util/document-node.js
As part of #623, this adds footnotes to the bottom of tables. It's not styled well, but should get us started. It also converts some library functions into methods for ease of use.
Looks like
=> Convert node fns to OO, add table footnotes

ui/__tests__/components/content-renderers/footnote-citation.test.js, ui/components/content-renderers/footnote-citation.js, ui/css/base/_util.scss, ui/css/main.scss
This prevents the citation from breaking across lines.
=> Use white-space: nowrap in the footnote citation.

api/example_docs/m_16_19_1.xml, ui/components/node-renderers/list-item.js, ui/css/main.scss, ui/css/module/_listitem.scss
This should resolve the elements on #600 by tweaking the list item styles and replacing the bullet marker in the source XML.
=> Update list item styling

ui/__tests__/components/node-renderers/math.test.js
If a render fails
When nobody can hear it
Now we might find out.
Add a basic test for the KaTeX math component.
=> Add simple test for KaTeX math component

ui/.eslintrc, ui/__tests__/components/app-wrapper.test.js, ui/__tests__/components/content-renderers/footnote-citation.test.js, ui/__tests__/store.test.js, ui/components/app-wrapper.js, ui/components/content-renderers/footnote-citation.js, ui/npm-shrinkwrap.json, ui/package.json, ui/store/actions.js, ui/store/index.js, ui/store/initial-state.js, ui/store/reducer.js
This resolves #621 by pushing the which-footnote-is-expanded logic into redux. It's overkill for our single bit of state, but should bootstrap this style of state management.
CC @tadhg-ohiggins for visibility
=> Ensure only one footnote is opened at a time

ui/components/content-renderers/footnote-citation.js, ui/css/base/_colors.scss, ui/css/layout/_markers.scss, ui/css/main.scss, ui/css/module/_footnotes.scss, ui/css/module/_listitem.scss
As part of #624, this
* Changes color of border
* Changes indent for marker
* Shrinks font size a bit
* Ensures long URLs are wrapped
* Makes marker text bold
* Attempts to line up marker text with footnote text
It also moves the `cite` tag to be more semantic and prevent italic text from appearing in our inline footnotes.
It also adds a new color variable since the requested color wasn't present. I've opened #648 to try to resolve that more permanently.
=> Style bottom policy footnotes

ui/__tests__/components/link.test.js, ui/components/content-renderers/footnote-citation.js, ui/components/link.js, ui/css/module/_footnotes.scss
Fixes #633.
Notes:
* `role="alertdialog"` for the pop-up footnote might not be ideal, but it's the closest thing I could find that seemed to work on screen readers.
* I replaced the footnote `<Link>` with an `<a>` because I couldn't figure out how to get a reference to the DOM node for the link otherwise (when I put a `ref` on the `<Link>` it was called back with `null` as its first argument). I thought it would be okay since we're not actually using this link for any next.js-specific functionality, e.g. next.js isn't intercepting clicks and diverting them to `pushState` here or anything.
* I considered adding an `aria-haspopup="true"` to the footnote link, so screen-reader users would know what would happen when they activate the link, but apparently [`aria-haspopup` should only be used …
=> Fix footnote accessibility issues

ui/__tests__/components/content-renderers/footnote-citation-in-table.test.js, ui/__tests__/components/node-renderers/caption.test.js, ui/__tests__/components/node-renderers/fallback.test.js, ui/__tests__/components/node-renderers/footnote.test.js, ui/__tests__/components/node-renderers/heading.test.js, ui/__tests__/components/node-renderers/policy.test.js, ui/__tests__/components/node-renderers/table/tfoot.test.js, ui/__tests__/components/node-renderers/td.test.js, ui/__tests__/components/node-renderers/th.test.js, ui/__tests__/test-utils/node-factory.js, ui/__tests__/test-utils/node-renderers.js, ui/__tests__/test-utils/tables.js, ui/__tests__/util/render-contents.test.js, ui/__tests__/util/render-node.test.js, ui/components/content-renderers/footnote-citation-in-table.js, ui/components/content-renderers/footnote-citation.js, ui/components/node-renderers/caption.js, ui/components/node-renderers/fallback.js, ui/components/node-renderers/footnote.js, ui/components/node-renderers/heading.js, ui/components/node-renderers/para.js, ui/components/node-renderers/policy.js, ui/components/node-renderers/table/tfoot.js, ui/components/node-renderers/td.js, ui/components/node-renderers/th.js, ui/util/render-contents.js, ui/util/render-node.js
As part of #623, this renders footnote citations within tables differently than the rest of the document by:
1. allowing individual node renderers to override how their content is rendered
2. adding a custom renderer for footnote citations for use within tables.
The big change about the former is a change in the way we render content (specifically, inline text, citations, etc.) Rather than having `renderNode` pass the rendered content along, this pushes the render logic into the components:
```jsx
<Footnote docNode={docNode}>
{ renderContents(docNode.content) }
</Footnote>
function Footnote({ children, docNode }) {
return <div id={docNode.identifier}>{ children }</div>;
}
```
becomes:
```jsx
<Footnote docNode={docNode} />
function Footnote({ docNode }) {
return <div …
```
=> Alter footnote citations in a table

api/example_docs/m_16_19_1.xml, ui/__tests__/components/node-renderers/math.test.js, ui/__tests__/util/document-node.test.js, ui/components/node-renderers/math.js, ui/util/document-node.js
This hacks around some missing functionality in KaTeX (the ability to include
links) by inserting markdown syntax for a link and replacing it with an `a`
tag _after_ running it through the KaTeX transform.
This should get simpler once KhanAcademy/KaTeX#923 is merged, but until then, I think it'll do.
Note that the anchor this links to won't be functional until #654 is merged.
This should resolve #625
=> Footnote citation links in maths!

ui/components/content-renderers/footnote-citation-in-table.js, ui/components/node-renderers/table/tfoot.js, ui/css/base/_colors.scss, ui/css/main.scss, ui/css/module/_tables.scss
Adds the gold background and adjusts spacing, font-sizes for footnotes at the bottom of tables and footnote citations within tables.
=> Style footnotes & their citations in tables

ui/css/module/_footnotes.scss
This style was accidentally lost in some class renaming and PR splitting.
=> Remove focus outline.

api/reqs/serializers.py, api/reqs/tests/views_policies_tests.py, api/reqs/views/policies.py, ui/__tests__/components/policies/policy-view.test.js, ui/components/policies/policy-view.js
One day, this might fix #556, but for now
Interesting things that have happened so far:
* ~~I originally tried adding a property to the policy API response called `docnode_count`, but this caused next.js to fail while rendering the homepage, claiming that it was being asked to JSONify a self-referential object. I have no idea why it felt that way, but renaming the field to `boop` somehow fixed things.~~ **Update:** CM explained the error and I've filed #665 separately.
* ~~Even once I called the field `boop` and it showed up in unit tests, it still wasn't showing up in API responses.  Eventually I did `docker-compose up dev-api` and intentionally broke the API by adding a nonsensical field, and when I fixed it and the server restarted itself, `boop` was in the API responses. So I guess …
=> [WIP] Attempt to link to policy detail

ui/css/module/_header.scss
Add vertical margin on navbar after removing Chrome default settings.
=> Re-add vertical padding on nav bar

ui/__tests__/components/contact-email.test.js, ui/__tests__/components/disclaimer.test.js, ui/__tests__/components/link.test.js, ui/__tests__/components/pagers.test.js, ui/__tests__/pages/privacy.test.js
eslint-plugin-jest added a rule around preferring toHaveLength() in 21.3.0;
let's follow it.
=> Prefer .toHaveLength() over .length).toEqual().

api/document/serializers/content.py, api/document/serializers/doc_cursor.py, api/document/tests/serializers/content_test.py, api/document/tests/serializers/doc_cursor_test.py, api/requirements.in, api/requirements.txt, api/requirements_dev.txt
This alters the API to include nested inline elements as a tree structure, with PlainText/__text__ leaf nodes. Parent content's "text" attribute continues to include the full text, so there's no immediate need for a corresponding change in the UI.
This should resolve #689
=> Allow nested content

api/document/serializers/content.py, api/document/tests/serializers/content_test.py, ui/__tests__/components/content-renderers/external-link.test.js, ui/__tests__/components/content-renderers/requirement.test.js, ui/components/content-renderers/external-link.js, ui/components/content-renderers/requirement.js, ui/css/base/_colors.scss, ui/css/module/_footnotes.scss, ui/css/module/_requirements.scss, ui/util/render-contents.js
This is the mirror of #706, taking the data from the API and displaying it in the user interface. It also allows external links to include other types of annotations and fixes an issue with the nesting logic.
Looks like (with #706 and #712)
=> UI for inline requirements

ui/__tests__/util/api/queries.test.js, ui/util/api/queries.js
Django Rest Framework returns a 404 when the user requests a non-existent page
number in a listing. Previously, we didn't account for that in the UI and just
raised the exception. This resolves by reusing our existing propagate404
function on the listing pages.
It might make sense to apply this to _all_ listing endpoints, but I've not
thought through the ramifications enough to be confident that that's a good
idea.
This should resolve #691
=> Propagate 404s from the API for paging errors.

ui/css/module/_footnotes.scss, ui/css/module/_tables.scss
Pulls in some of the content from #679 and adds a tweak to footnote citation line height:
=> Minor style updates

ui/components/content-renderers/plain-text.js, ui/components/header-footer.js, ui/components/policies/policies-view.js, ui/components/requirements/requirements-view.js
We had been wrapping these elements in a div or a span because React <16
didn't know how to render "partial" elements: plain strings or array.
This isn't a huge change in terms of file size (we drop ~2k off M-16-18), but
it does make the markup much cleaner.
=> Remove extraneous divs/spans.

ui/__tests__/components/document/navigation-heading.test.js, ui/__tests__/components/document/navigation.test.js, ui/__tests__/pages/document.test.js, ui/components/document/navigation-heading.js, ui/components/document/navigation.js, ui/components/node-renderers/policy.js, ui/components/node-renderers/table/tfoot.js, ui/css/base/_colors.scss, ui/css/layout/_layout.scss, ui/css/module/_document.scss, ui/pages/document.js, ui/util/document-node.js
This adds components to represent the document navigation menu. It uses the data from #737 for population (meaning we'll need to re-import that doc).
This does _not_ implement mobile, navigation stickiness, or highlighting the user's current position (which are all separate tickets).
Looks like
Should resolve #733
=> Add desktop navigation

ui/__tests__/components/app-wrapper.test.js, ui/components/app-wrapper.js, ui/pages/privacy.js
The app-wrapper sets up redux (along with some error handling, etc.), so it's
important it be called at all entrypoints. Notably, if a user can do AJAX, but
initially loads the privacy page (which wasn't wrapped), they'll receive an
error when trying to use redux on the document page.
To do this, we needed to allow pages to have a no-op data fetching function.
=> Ensure all /pages are wrapped.

docker-compose.yml, ui/.docker/modify_path_then
I've been using these commands from my own machine for a while--except I have them as shell scripts, basically--and I thought it might be convenient to have them as commands in our `docker-compose.yml`:
* `docker-compose run --rm pybash` starts a bash session in the Python container, providing easy access to any Python-related tooling with minimal fuss.
* `docker-compose run --rm nodebash` does the same, but for the node container. It also adds the ui's `node_modules/.bin` to the `PATH` for easy access to node tooling.
There's a few reasons why I prefer these over the various commands that are currently in our `docker-compose.yml`:
* Starting up docker always takes a little while, and this setup time adds up when running multiple commands in quick succession.  In contrast, the `*bash` …
=> Add 'pybash' and 'nodebash' commands to docker-compose.yml

api/ombpdf/document.py, api/ombpdf/download_pdfs.py, api/ombpdf/fontsize.py, api/ombpdf/footnotes.py, api/ombpdf/horizlines.py, api/ombpdf/html.py, api/ombpdf/lists.py, api/ombpdf/pagenumbers.py, api/ombpdf/paragraphs.py, api/ombpdf/rawlayout.py, api/ombpdf/semhtml.py, api/ombpdf/semtree.py, api/ombpdf/tests/bbox.py, api/ombpdf/tests/conftest.py, api/ombpdf/tests/test_doctests.py, api/ombpdf/tests/test_eqnamedtuple.py, api/ombpdf/tests/test_headings.py, api/ombpdf/tests/test_html.py, api/ombpdf/tests/test_lists.py, api/ombpdf/tests/test_pagenumbers.py, api/ombpdf/tests/test_paragraphs.py, api/ombpdf/tests/test_semhtml.py, api/ombpdf/tests/test_webapp.py, api/ombpdf/underlines.py, api/ombpdf/util.py, api/requirements.in, api/setup.cfg
Following up on #757, this re-enables linting on ombpdf and a few other things.
* Wow, I didn't know about the actual [`isort` command-line program](https://pypi.python.org/pypi/isort). That made some of this a lot easier!
* The visitor pattern used for serializing semantic trees used to do dynamic dispatch by calling a method that had a camel-cased class name in it, but this upset the linter for obvious reasons, so I changed the convention to use an underscored version of the class name instead.
* Doctests from `ombpdf` are now tested. As mentioned in #757, enabling doctest finding in pytest across the whole codebase resulted in a mysterious segfault, and there didn't seem to be any way to scope doctest-finding only to specific directories, so instead I just added a `test_doctests.py` …
=> Lint ombpdf, and a few other fixes

ui/__tests__/components/document/footnotes.test.js, ui/__tests__/components/node-renderers/policy.test.js, ui/__tests__/pages/document.test.js, ui/__tests__/store.test.js, ui/__tests__/util/with-scroll-tracking.test.js, ui/components/document/footnotes.js, ui/components/node-renderers/policy.js, ui/pages/document.js, ui/store/actions.js, ui/store/reducer.js, ui/util/render-node.js, ui/util/with-scroll-tracking.js
Building on #752 ([diff](https://github.com/18F/omb-eregs/compare/735-hl-section...735-hl-footnotes)), this adds a "Footnotes" section to the bottom of the table of contents (when footnotes are present). It also wraps the footnotes with scroll tracking to highlight the correct section.
Looks like:
=> Create/highlight "Footnotes" section of ToC

api/omb_eregs/settings.py
pdfminer has a *lot* of informational logging output, which spams the logs during development, so this changes it to only log warnings/errors.
The change in behavior can be seen by running e.g. `manage.py pdf_fonts data/2016/m_16_19_1.pdf`.
=> Only log warnings from pdfminer

ui/pages/document.js
Our "Sticky" library has a bug around activation on initial page load. This
works around that by triggering a mock scroll event on DOM mount.
=> Work around react-stickynode bug.

ui/components/navbar.js, ui/css/base/_media-queries.scss, ui/css/layout/_markers.scss, ui/css/layout/_typography.scss, ui/css/main.scss, ui/css/module/_header.scss, ui/pages/document.js
As part of #734, this adds some scss to differentiate mobile from desktop views. It then uses those to tweak the mobile header. @rtwell's agreed that these changes are a step in the right direction (though we won't implement a full redesign this sprint).
Looks like:
=> Tweak mobile header, begin to standardize on media

ui/__tests__/components/document/floating-nav.test.js, ui/__tests__/components/document/navigation/index.test.js, ui/__tests__/components/document/navigation/nav-link.test.js, ui/__tests__/components/document/sidebar-nav.test.js, ui/__tests__/pages/document.test.js, ui/components/document/floating-nav.js, ui/components/document/navigation/index.js, ui/components/document/navigation/nav-link.js, ui/components/document/sidebar-nav.js, ui/components/startup-sticky.js, ui/css/base/_colors.scss, ui/css/base/_util.scss, ui/css/module/_document.scss, ui/pages/document.js
Building on on #766 and #769, this adds a first pass at mobile, in-document navigation. This component has an open/closed state and is progressively enhanced out of the "open" state for modern JS users.
Some caveats:
* It doesn't try to resolve the heading-under-floating-title issue.
* This'll need to use the fixed sticky library from #762 once it's merged.
* Code climate rightfully points out some deeply-nested styles. I'd prefer if we didn't have these, but I also don't see a nice way out.
Looks like
=> Mobile, in-document navigation

ui/components/document/footnotes.js, ui/components/node-renderers/table/tfoot.js, ui/css/module/_document.scss, ui/css/module/_footnotes.scss
Notably:
* The "Top" link
* The "Footnotes" link
* Links to footnotes at the bottom of a table
Unfortunately, we can't do something like `[id]::before {` because it creates a line break before inline elements.
=> Account for floating nav offset in more places

ui/__tests__/util/api/queries.test.js, ui/util/api/endpoints.js, ui/util/api/queries.js
When a user doesn't have JS, the topic search falls back to a text field which
is passed around via POSTs. If the backend API returned a 404 (as is the case
with bad page numbers), we weren't passing that to the user.
To see it in action, visit: 
```
/search-redirect/topics/?insertParam=requirements__topics__id__in&redirectRoute=policies&q=security&redirectQuery__requirements__req_text__search=&page=44
```
=> Resolve 500 error when search 404ed.

ui/__tests__/components/homepage/new-policy-view.test.js, ui/__tests__/components/node-renderers/policy.test.js, ui/__tests__/pages/policies.test.js, ui/__tests__/util/api/queries.test.js, ui/__tests__/util/policy.test.js, ui/components/homepage/new-policy-view.js, ui/components/node-renderers/policy.js, ui/components/policies/policies-view.js, ui/components/policies/policy-view.js, ui/pages/index.js, ui/pages/policies.js, ui/util/api/queries.js, ui/util/document-node.js, ui/util/policy.js
We had defined a `Policy` object for use on the policy search results page. This defines that object's fields a bit more closely and uses it on the homepage and in document metadata.
This came up while adding page titles.
=> Standardize "Policy" object across three pages

api/document/serializers/meta.py, api/document/tests/serializers/doc_cursor_test.py, ui/__tests__/pages/document.test.js, ui/__tests__/pages/policies.test.js, ui/__tests__/pages/privacy.test.js, ui/__tests__/pages/requirements.test.js, ui/__tests__/util/page-title.test.js, ui/components/header-footer.js, ui/components/startup-sticky.js, ui/pages/document.js, ui/pages/policies.js, ui/pages/privacy.js, ui/pages/requirements.js, ui/pages/search-redirect.js, ui/util/page-title.js
Building off #775 ([diff](https://github.com/18F/omb-eregs/compare/699-policy-object...699-page-titles)), this ensures every page sets a title. The only interesting bit here is that the "document" page sets its title to the policy's title-with-number.
=> Add a page title for every page

api/ombpdf/document.py, api/ombpdf/footnotes.py, api/ombpdf/html.py, api/ombpdf/semdom.py, api/ombpdf/semhtml.py, api/ombpdf/semtree.py, api/ombpdf/tests/test_footnotes.py, api/ombpdf/tests/test_html.snapshot.html, api/ombpdf/tests/test_semdom.snapshot.m_16_19_1.xml, api/ombpdf/tests/test_semhtml.snapshot.html
~~This fixes the core problem presented by #782, though it doesn't actually resolve that issue itself, because it still keeps the full text of a footnote as part of the `OMBFootnote` annotation. Actually fixing the latter will take some effort because the footnote tests rely on it so much, but it's not that high a priority.~~
This fixes #782.
Note that we don't actually _have_ any inline rich text markup in `semtree.py`, so this doesn't actually do a whole lot, but eventually we will support inline rich text markup, so it's nice to know it'll automatically work okay when it's in footnotes.
The changes in the snapshot files are due to us delegating the content of footnotes to the same logic we use for any block content, like paragraph text.  Because this logic is slightly different from …
=> Support (eventual) inline rich text markup in footnotes

.gitignore, ui/components/header-footer.js, ui/css/main.scss
We can embed the CSS directly from our local node package, which ensures the
CSS and JS stay in sync.
=> Remove CDN'd version of KaTeX css.

ui/css/base/_spacing.scss, ui/css/base/_type-size.scss, ui/css/layout/_layout.scss, ui/css/layout/_typography.scss, ui/css/main.scss, ui/css/module/_document.scss, ui/css/module/_footnotes.scss, ui/css/module/_header.scss, ui/css/module/_homepage.scss, ui/css/module/_listitem.scss, ui/css/module/_node-heading.scss, ui/css/module/_policies.scss, ui/css/module/_tables.scss
Per #718, this:
* Removes gold from h4 headings
* Uses the same font size/line height for numbered lists
* Adjusts spacing between headings
It also adds some variables/mixins to start the process of standardizing our font sizes and spacing, per discussion last sprint with @rememberlenny and @rtwell 
Looks like
=> Visual tweaks to document

api/document/renderers.py, api/document/templates/rest_framework/api.html, api/document/tests/renderers_test.py, api/document/views.py
This minorly builds on #795 by making the AKN renderer easy to browse, which I think could be helpful for debugging. Currently, clicking the "akn" format in the browsable API (under the "GET" button/popup) triggers a download, which one then has to find and open in their text editor, whereas this PR adds an "akn-api" format that [trivially customizes `BrowsableAPIRenderer`](http://www.django-rest-framework.org/api-guide/renderers/#customizing-browsableapirenderer) to present the XML response in a syntax-highlighted web view, similar to how the normal JSON responses are presented:
> ![screenshot-2017-12-20 tree omb policy library api beta](https://user-images.githubusercontent.com/124687/34234182-932ce1be-e5b7-11e7-9d32-bc6e461d64fd.png)
It also overrides `rest_framework/api.html`'s [`{% …
=> Add a BrowsableAkomaNtosoRenderer

ui/__tests__/components/node-renderers/list-item.test.js, ui/components/node-renderers/list-item.js, ui/css/module/_listitem.scss, ui/util/document-node.js
We've seen multiple policies where individual list items have an associated
title/heading. This modifies our renderers to display that, if present.
Looks like (after mocking out some data):
=> Display list item titles, if present.

api/ombpdf/management/commands/scrape_memoranda.py, api/ombpdf/tests/test_management_commands_scrape_memoranda.py
OMB keeps a list of all their memoranda. Rather than manually downloading and
loading each PDF into the database, we can scrape that list and load them all
at once. This'll allow us to verify them much more quickly and make importing
them into an empty database much easier.
Using current db importer
* 92 imports
* 54 exceptions
Using the #799 importer
* 110 imports
* 36 exceptions
=> Add script for scraping & loading memoranda.

api/.docker/watch_tests.sh, api/document/models.py, api/document/tests/serializers/doc_cursor_test.py, api/document/tests/tree_test.py, api/document/tests/views_test.py, api/document/tests/xml_importer/annotations_test.py, api/document/tree.py, api/ombpdf/semdb.py, api/ombpdf/tests/test_semdb.py, api/setup.cfg
Rather than writing to XML then importing from that, this has the pdf import write directly to the database. Along the way, it also enables ombpdf tests from the py.test and ptw docker commands.
=> Skip intermediary XML layer from pdf

.circleci/config.yml, .gitignore, README.md, api/mypy-files.txt, api/mypy.ini, api/requirements_dev.in, api/requirements_dev.txt, docker-compose.yml
This attempts to productionalize some experimentation I did in #798 by running [mypy](http://mypy.readthedocs.io/) on a whitelist of our source files (stored in `api/mypy-files.txt`).  This allows us to easily opt-in to type checking without slowing us down.
Currently the mypy settings are _very_ lax, which I've found is generally good for legacy codebases and code that uses third-party libraries that lack type annotations (like Django), since it makes it possible to ["sprinkle in" type checking in a targeted way](https://github.com/18F/calc/pull/1505#issuecomment-288855201), e.g. based on where it'd be most useful.
If this seems amenable, I can add documentation for it to `README.md` in which I also explain our approach, which could help with #410.
=> Run mypy on whitelisted files.

api/ombpdf/js/bbox.ts, api/ombpdf/js/in-viewport.ts, api/ombpdf/js/main.js, api/ombpdf/js/main.ts, api/ombpdf/js/render-pdf.ts, api/ombpdf/js/tooltip.ts, api/ombpdf/package.json, api/ombpdf/tsconfig.json, api/ombpdf/webpack.config.js
This is really just meant to build a TypeScript foundation on the API-side, so that we can use TS to implement the productionalized version of the front-end from #798.
I figured I might as well convert my hackneyed JS devtool code for ombpdf into TypeScript as a way to refresh myself on how TypeScript works, so I did that. Note, though, that I didn't have to do a full conversion--I actually started by just converting one file to TS--because TypeScript plays nicely with regular 'ol JS.
=> Convert ombpdf JS to TypeScript

api/ombpdf/document.py, api/ombpdf/management/commands/scrape_memoranda.py, api/ombpdf/semdb.py, api/ombpdf/tests/test_document.py, api/ombpdf/tests/test_management_commands_scrape_memoranda.py, api/ombpdf/tests/test_semdb.py
These prevent explosions when importing docs that:
* Don't have a clear left margin
* Have footnote citations, but no footnote list
* Have no text (i.e. image-only)
=> Resolve a handful of pdf importing exceptions

api/omb_eregs/settings.py
This'll allow us to run the PDF scraping scripts. The associated views are
still hidden behind a DEBUG flag.
=> Enable ombpdf in production.

.circleci/config.yml, .gitignore, api/document/js/__tests__/example-doc.test.ts, api/document/js/example-doc.ts, api/document/js/keyboard.ts, api/document/js/main.ts, api/document/js/menu.ts, api/document/js/schema.ts, api/document/js/state.ts, api/jest-ts-preprocessor.js, api/package.json, docker-compose.yml
~~**Note that this is currently a PR against #809, not `master`.**~~
This builds upon #809 by adding support for Jest, along with one simple test.
Unfortunately, in doing so, it refactors a bunch of #809 by splitting up `main.ts` into a bunch of files, which muddles things up a bit.  Sorry about that...
=> Add Jest support to API JS

.circleci/config.yml, README.md, api/.docker/wait_for_db_then, api/.docker/wait_for_webpack_then, api/ereqs_admin/static/admin/override.scss, api/ereqs_admin/templates/admin/base_site.html, api/omb_eregs/settings.py, api/package.json, api/requirements.in, api/requirements.txt, api/requirements_dev.txt, api/webpack.config.js, docker-compose.yml
We know we'll want to reskin a significant chunk of the Django admin. Although [django-admin-interface](https://github.com/fabiocaccamo/django-admin-interface) will get us close, we'll likely want to override other styles as well.
This adds a config for building a SCSS bundle to the api webpack and includes that in the Django admin. The SCSS file includes a commented style, which quickly tests that everything works.
=> Foothold for custom styles in Django admin

api/document/tests/json_importer/annotations_test.py, api/document/tests/json_importer/factories.py, api/document/tests/json_importer/importer_test.py
This gets rid of a janky code smell introduced in #815. whereby one of our test suites was importing factory functions and fixtures introduced in an unrelated test suite. It also hopefully lays some groundwork for less verbose JSON and/or serializer-related tests going forward.
=> Factor out tests/json_importer/factories.py

api/document/serializers/content.py, api/document/tests/serializers/content_test.py
This un-janks [another yucky hack](https://github.com/18F/omb-eregs/pull/815#discussion_r160726424) introduced in #815 by un-bloating the `BaseAnnotationSerializer` a bit:
* The `text` field is now its own serializer field. Note the comment on its `to_internal_value` method, it's a bit funky.
* The `inlines` field is now its own serializer field. If `inlines` is non-empty on a leaf node (i.e., `__text__`), we raise a validation error, as suggested by @cmc333333 at some point, I think.
=> Factor out InlinesField and TextField in serializers/content.py

api/document/serializers/content.py, api/document/tests/serializers/content_test.py, api/mypy-files.txt
This fixes #826 and also makes the module's annotation-to-serializer mapping a bit more understandable (maybe) by introducing a `NestedAnnotationSerializer.register` decorator that "registers" an annotation serializer with the system.
Both changes are in separate commits, so if we dislike one we can just commit the other.
=> Fix type annotations in document.serializers.content

api/document/tests/doctest_test.py, api/document/tree.py
This documents our `DocCursor` model a bit more.  I ended up also adding a `__str__()` implementation to it (though we could rename it to `describe()` or something if we don't like the idea of `__str__()` returning multiple lines of text) to make it easier to see what a cursor is "pointing" at.
Note that the documentation is tested via a weird `doctest_test.py` that's largely copy-pasted from #758.  As mentioned in that issue, it's a workaround because enabling doctest finding in pytest across the whole codebase results in a mysterious segfault. What's also unfortunate is that if the test fails, it produces unhelpful output; the most helpful output can be found by running `pytest --doctest-modules document/tree.py` (which doesn't segfault because it's only looking at one file). …
=> Add documentation for DocNode, Annotation, and DocCursor (w/ doctests)

api/document/serializers/doc_cursor.py, api/document/tests/serializers/doc_cursor_test.py
This attempts to decouple the `DocCursorSerializer` from DRF's `ModelSerializer`. For rationale, see the included docstring for `docnode_field_attrs`.
I was really hoping this would get rid of our need for the ugly `_prefetched_objects_cache` in `DocCursor`, but that is actually accessed by DRF's `UpdateModelMixin` (inherited by our `TreeView` view), _not_ `ModelSerializer`.  I still think the decoupling in this PR may generally be a good idea though... and I can issue a future PR (or add onto this one) that decouples us from the `UpdateModelMixin`.
=> Decouple the DocCursorSerializer from ModelSerializer

api/document/tree.py, api/document/views.py
This builds upon #861 and decouples `document.views.TreeView` from its Django-model-specific mixins, allowing us to get rid of the `DocCursor._prefetched_objects_cache` hack introduced in https://github.com/18F/omb-eregs/pull/815#pullrequestreview-87544955.
Note that the added code here is identical to what's in the original mixins that the `TreeView` previously used, with the exception of code that examined `_prefetched_objects_cache` and a bit of code that supported partial updating (which honestly, I don't even know if our serializer could support that right now, so I figure we can add it back if/when we need to). Concretely, that's [`RetrieveModelMixin` and `UpdateModelMixin`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/mixins.py#L51-L84) and …
=> Get rid of DocCursor._prefetched_objects_cache hack

api/document/serializers/content.py, api/document/tests/serializers/doc_cursor_test.py, api/document/tests/views_test.py, api/document/views.py
This builds upon #868 by adding the Akoma Ntoso parser to our `TreeView` so clients can PUT Akoma Ntoso documents via the REST API.
Note that this PR does _not_ currently add `defusedxml` because I'm confused about whether it's actually needed, as explained in https://github.com/18F/omb-eregs/pull/868#issuecomment-358361139.  @cmc333333 let me know if you think I should add it, otherwise I'll leave it off!
=> Support PUT requests w/ content type akn+xml

api/document/js/__tests__/fetch-doc.test.ts, api/document/js/__tests__/schema.test.ts, api/document/js/fetch-doc.ts, api/document/js/schema.ts
This
* Resolves #871 by avoiding text nodes within `unimplemented_node`
* Swaps our conversion step to using ProseMirror's node factories rather than raw objects
* Sets up the "para" and "sec" types. The former breaks from #798 a bit as it moves all of the text content into a single ProseMirror type ("inline") and only includes that at most once.
This doesn't handle the API's `content` (ProseMirror's `mark`) types; that'll be the next step.
=> Add "para" and "sec" node types to editor

api/omb_eregs/settings.py
By default, Django uses `/accounts/` urls for login redirects. We're only
using logins with the admin, however, so it makes sense to redirect to the
admin-specific sections.
This resolves #877.
=> Ensure logins redirect to the admin screens.

api/ereqs_admin/static/admin/override.scss
We didn't finish the styling for this menu, so this disables it. The changeset does make activation/deactivation as simple as flipping a variable, though.
=> Disable admin nav menu

api/ombpdf/management/commands/import_pdfs_from_policies.py
We have stricter memory limits in our cloud.gov environment than on our
development machines. This adds exceptions for a handful of pdfs that could be
processed locally, but can't in cloud.gov.
=> Add a few "problem" policies.

api/document/js/__tests__/fetch-doc.test.ts, api/document/js/fetch-doc.ts, api/document/js/schema.ts, api/package-lock.json, api/package.json
This handles nested content by keeping a stack of derived markers and
linearizing them into an array of `text`s (each with the stack of marks).
Similar to the unimplemented_node, we want to track all of the meta
information around an unknown content/annotation/inline/mark type (yay
different names for similar concepts!).
Looks like
=> Add initial "mark" support to editor import.

api/document/tests/end_to_end_test.py
This attempts to help with #924 by adding an end-to-end test for AKN using a real-world policy (M-16-19).
It is kind of convoluted, and I'm not sure how useful it is. It did, however, help me realize that the preamble of our XML example documents is actually part of the document that's stored in the database, which I hadn't realized--I thought the preamble was solely stored as metadata on the `Policy` model, but it actually seems to be stored in _both_ the `Policy` _and_ under a `preamble` node type in the document. But because some/all of our DRF pipeline ignores it, it gets lost at some point.
Because of this discrepancy, and a few others that I didn't investigate terribly closely, I ended up doing more round-trips between the AKN parser/renderer than I had originally intended. I'm not …
=> Add an end-to-end test for AKN

api/document/js/__tests__/fetch-doc.test.ts, api/document/js/__tests__/save-doc.test.ts, api/document/js/fetch-doc.ts, api/document/js/keyboard.ts, api/document/js/save-doc.ts, api/document/js/schema.ts, api/package-lock.json
This adds an initial serializer for the ProseMirror data, which is triggered on Ctrl/Cmd-s. This doesn't actually write to the API yet; I need to refactor the components shared with the AKN editor first. I figured this was already big enough for review.
=> Serialize ProseMirror data

api/ombpdf/management/commands/import_pdfs_from_policies.py, api/ombpdf/management/commands/scrape_memoranda.py, api/ombpdf/tests/test_management_commands_scrape_memoranda.py, api/reqs/models.py, api/reqs/serializers.py, api/reqs/tests/model_tests.py, api/reqs/tests/views_policies_tests.py, api/reqs/views/policies.py, ui/__tests__/components/policies/policy-view.test.js, ui/__tests__/util/policy.test.js, ui/components/policies/policy-view.js, ui/util/policy.js
This resolves #678 by linking to the document page when a policy doesn't have an M-number.
It also checks the workflow phase field rather than the presence/absence of docnodes when determining what to link to. Note, however, this means we'll be removing all our current links. I figure we can use the admin to adjust where desired, but we can also do a data migration if there's a better option.
=> Link to document by slug, look at workflow phase

api/document/json_importer/annotations.py
This reverts commit 18b3160d5e764b0e2520b410bae99eae2f3c5e9f, introduced in #884, and fixes #903.
=> Revert "Footnote-finder also looks for matching 'marker'."

api/document/json_importer/annotations.py, api/document/tests/factories.py, api/document/tests/json_importer/annotations_test.py
This adds support for the `Cite` annotation type to the JSON importer.
This clears the path to #923, as `example_documents/m_15_16.xml` has `<cite>` annotations that can only be imported by the legacy XML importer at the moment.
=> Add support for 'cite' anno type to json_importer

api/document/js/Api.ts, api/document/js/__tests__/Api.test.ts, api/document/js/__tests__/parse-doc.test.ts, api/document/js/__tests__/serialize-doc.test.ts, api/document/js/akn/main.ts, api/document/js/create-editor-state.ts, api/document/js/keyboard.ts, api/document/js/main.ts, api/document/js/parse-doc.ts, api/document/js/serialize-doc.ts, api/document/templates/document/editor.html, api/document/templates/document/editor_akn.html, api/document/views.py, api/ereqs_admin/static/admin/module/_editor.scss, api/ereqs_admin/static/admin/override.scss
This moved and combined templates, stylesheets, and a shared Api module so that the ProseMirror editor can re-use a goodly chunk of the AKN logic. With that, it was pretty straight forward to add a save function.
This is a lot of changes in terms of line count, but much of it is composed of renaming and moving functions around.
=> Save data from prosemirror

api/document/renderers.py, api/document/tests/renderers_test.py
This helps with (possibly fixes?) #901 by getting rid of the `CONTENT_TYPES` whitelist in `document.renderers` and replacing it with a `NON_CONTENT_ATTRIBS` blacklist.  This means that new annotation types should be easier to add in the future, since developers won't have to worry about adding stuff to `CONTENT_TYPES`.
=> Make rendering of AKN content attribs use blacklisting

api/omb_eregs/settings.py, api/requirements_dev.in, api/requirements_dev.txt
This fixes #876 by removing `pyinotify`, and it also adds [`radon`](https://pypi.python.org/pypi/radon), which is what Code Climate uses for various metrics like cyclomatic complexity. Having it in our development dependencies will make it easier to reproduce CC feedback locally.
=> Remove pyinotify, add radon

api/ereqs_admin/static/admin/layout/_typography.scss, api/ereqs_admin/static/admin/override.scss, shared-styles/base/_type-size.scss, shared-styles/module/_paragraph.scss, ui/css/layout/_typography.scss
This should resolve #916 and #917 by overriding the default fonts in Django's admin. Not a radical change, but worth the consistency.
=> Override fonts in Django admin, editor

api/document/serializers/content.py, api/document/serializers/doc_cursor.py, api/document/serializers/util.py, api/document/tests/serializers/content_test.py, api/document/tests/serializers/doc_cursor_test.py
This helps with #904 by making `ValidationError` exceptions raised by our `DocCursorSerializer` less vague, in that they will contain enough data to allow someone to figure out _where_ in their payload a validation error occurred. See https://github.com/18F/omb-eregs/issues/904#issuecomment-360800292 for more details.
=> Make ValidationErrors more detailed/accurate

api/document/serializers/content.py, api/document/serializers/doc_cursor.py, api/document/tests/serializers/content_test.py, api/document/tests/serializers/doc_cursor_test.py
This fixes #957.
I find validation for DRF very confusing; in _some_ cases, [such as simple fields](http://www.django-rest-framework.org/api-guide/fields/#raising-validation-errors), it's recommended to raise one with a string `detail` during `to_internal_value()`. The DRF code that calls this method takes care of turning such errors into ones with dict-based `detail`.
However, in _other_ cases, such as [deserializers with multiple fields](http://www.django-rest-framework.org/api-guide/serializers/#overriding-serialization-and-deserialization-behavior), there are multiple options, one of which is also raise a `ValidationError` during `to_internal_value()`, _except passing a dictionary instead of a string for `detail`_.  This is super confusing and DRF doesn't even seem to care whether we …
=> Ensure ValidationErrors raised by serializers are dictionaries

api/document/js/__tests__/parse-doc.test.ts, api/document/js/__tests__/serialize-doc.test.ts, api/document/js/parse-doc.ts, api/document/js/schema.ts, api/document/js/serialize-doc.ts, api/ereqs_admin/static/admin/override.scss, shared-styles/base/_util.scss, shared-styles/layout/_markers.scss, shared-styles/module/_list.scss, ui/components/node-renderers/list.js, ui/css/main.scss
This displays lists and list items, including their marker text using the same styles (sans fonts) used in the frontend. There's no way to add a new list item at the moment, but this should get us started.
This allows the marker text (e.g. "1.") to be edited, which will likely be overly confusing for end users. We'll need to figure out what to do there as a team.
Looks like (please ignore misalignment due to font sizes)
=> Initial editor implementation for displaying/editing lists

api/document/serializers/content.py, api/document/serializers/doc_cursor.py, api/document/serializers/util.py
This improves upon #959 by using our `Serializer` subclasses the proper way for deserialization, e.g. by passing `data` to their constructor, then calling `.is_valid()`, then returning `.validated_data`.  Also, since we're no longer calling `to_internal_value()` directly and expecting a list back instead of a dict, mypy is no longer confused, which removes the need for that [`list_to_internal_value()` hack](https://github.com/18F/omb-eregs/pull/959#discussion_r164209536). Hooray! 🎉
=> Improve Serializer deserialization propriety

api/document/parsers.py, api/document/serializers/content.py, api/document/serializers/doc_cursor.py, api/document/serializers/util.py, api/document/tests/parsers_test.py, api/document/tests/serializers/content_test.py, api/document/tests/serializers/doc_cursor_test.py, api/document/tests/serializers/util_test.py
~~**Note: this PR is targeted against #959, not `master`.**~~
This helps with #904 by "annotating" validation errors with source line metadata. Accomplishing this requires two steps:
1. The AKN parser "annotates" each node and annotation object with a `_sourceline` property that indicates the line where the XML element representing the object came from.
2. During validation, our node and annotation serializers catch any raised `ValidationError`s and "annotate" them with the `_sourceline` property passed into them by the upstream parser. If the upstream parser didn't include a `_sourceline` property (e.g. DRF's default JSON parser), nothing additional is done. The `ValidationError` is then re-raised.
Here's example validation error output of an <code>&lt;external_link&gt;</code> tag that …
=> Add source line metadata to validation errors if possible

api/document/js/Api.ts, api/document/js/__tests__/create-editor-state.test.ts, api/document/js/__tests__/parse-doc.test.ts, api/document/js/__tests__/schema.test.ts, api/document/js/__tests__/serialize-doc.test.ts, api/document/js/create-editor-state.ts, api/document/js/parse-doc.ts, api/document/js/schema.ts, api/document/js/serialize-doc.ts
In a few spots, our ProseMirror schema is a bit complex (having required nodes, needing specific attributes, etc.). Rather than require we remember the schema, we can use factory methods with parameters for each of the relevant bits.
This also alerts the user on schema validation failure (we had been loading an invalid doc structure without knowing).
=> Use factories when creating ProseMirror nodes, alert on schema fail

api/document/js/__tests__/schema.test.ts, api/document/js/schema.ts
Building on #969, this fixes a bug in which deleting a paragraph in the ProseMirror frontend wouldn't delete its entry in the ProseMirror doc. Then that doc was serialized, it'd include an empty paragraph, which led to very unintuitive problems.
=> Fix delete-paragraph bug

api/document/tests/end_to_end_test.py
This is just a workaround for #974 for now, until we have enough time to investigate the intermittent failure more closely.
=> Skip JSON end-to-end test for now

api/document/js/__tests__/commands.test.ts, api/document/js/commands.ts, api/document/js/menu.ts
This builds on #969. We'll most likely want to do paragraph splitting, collapsing, and other fun logic, but this starts us off by allowing a paragraph to be added through a button press. We'll no doubt be re-working this soon.
=> Add button for add-paragraph

ui/css/main.scss, ui/css/shared-styles
ab5bce3e343281b8dd21861cfd99c3fd5c094d75 created a symlink that made a `shared-styles` folder and linked to SCSS through it.
However, symlinks on Windows are problematic, to say the least. Out-of-the-box, the use of this symlink breaks Windows docker setups. While it may _technically_ be possible to make it work, it's likely that it'd  require the very latest versions of Windows 10 and developer tools (git and docker, at the very least), and possibly additional preference-setting gymnastics.  This could be particularly problematic for folks who may be stuck in enterprise environment, so I think we probably shouldn't rely on symlinks if at all possible.
This PR fixes things by removing the symlink and directly referring to the folder in question.
=> Remove shared-styles symlink to support docker on Windows

api/document/tests/views_test.py, api/document/views.py, api/reqs/views/policies.py
Previously, we weren't allowing documents associated with non-public policies
from being loaded into the editor (nor could they be retrieved in the API).
This should allow *logged in* users to see both.
It also adds a permissions check to the document load logic, which it looks
like we forgot. We don't really worry about different user groups anywhere
(other than logged in vs non), but it's best to lay that groundwork now.
=> Allow non-public documents to be edited by admins.

api/omb_eregs/urls.py, api/reqs/admin.py, api/reqs/templates/admin/reqs/policy/change_form.html, api/reqs/templates/reqs/admin/submit_line.html, api/reqs/templatetags/policy_submit_row.py, api/reqs/tests/admin_tests.py
We'd like a stop-gap to get to the editor page from a policy, so we'll add a
new button at the bottom of the Policy change form. We call the Django
template tags and methods and copy-paste the minimum template to reduce
duplication.
=> Add "Save and edit document" to policy admin.

api/document/js/__tests__/Api.test.ts, api/document/js/__tests__/commands.test.ts, api/document/js/commands.ts, api/document/js/create-editor-state.ts, api/document/js/keyboard.ts, api/document/js/menu.ts, api/ereqs_admin/static/admin/module/_editor.scss
Per convo with @rtwell and @austinhernandez, this adds a "save" button and adds a path to get to the XML editor.
=> Add save buttons to the editor

api/runtime.txt, docker-compose.yml
Our deploys have been failing today as cloud.gov no longer supports 3.6.2.
=> Bump Python version.

api/document/js/__tests__/parse-doc.test.ts, api/document/js/schema.ts, api/document/js/serialize-doc.ts
As a first step towards allowing lists/markers to be added, this removes the ability to edit the list item marker.
=> Prevent list markers from being edited.

redeployer/runtime.txt
Prior to removing the deployer (#988) we need to keep it up to date. Fortunately, the redeployer is the last of our apps to deploy, so we're effectively deploying everything now (despite the builds being marked as failures).
=> Bump redeployer version

.circleci/config.yml, README.md, api/.docker/watch_tests.sh, api/package.json, bin/api-npm, bin/bandit, bin/flake8, bin/manage.py, bin/mypy, bin/pip-compile, bin/psql, bin/ptw, bin/py.test, bin/python, bin/ui-npm, ui/package.json
Having a `bin` directory of common scripts had worked really well on personal projects. It gives us an avenue for docker optimization and documents our expected entry points. We can still do `docker-compose run xxx yyy` for edge-case tools (though it's super cheap to add another shell script, too).
=> Wrap docker-compose run for most common scripts

api/ombpdf/tests/test_management_commands_import_pdfs_from_policies.py, docker-compose.yml
Just as we're currently skipping tests related to PDF upload functionality, I think we should comment out the related Docker functionality, so developers aren't confused by its presence (and, tangentially, to make the Docker setup leaner for the time being).
Another alternative may be to simply _remove_ the code instead of commenting it out; it can always be brought back by inspecting the original commit that removed it (which we could make easy to find, e.g. by linking to it from #993).
=> Comment out minio for now

.circleci/config.yml, api/.cfignore
Previously, we had been spinning up a remote Docker instance to run all of our
tests, linting, building, etc. This replaces that with CircleCI's native
Docker images, which allow us to share data much more easily between steps.
That requires we maintain yet another environment, but this version is _very_
similar to our docker-compose file; it just uses Circle's configuration
format.
Using the native Docker images allows us to split a CI run into multiple,
often-parallelizable "jobs", which will make our runs both quicker and give us
better feedback (we can see if _both_ lint _and_ tests fail, for example).
This cuts a test run by roughly half.
This should resolve #859. It may temporarily break nightly deployments (I'll add a separate PR for that). [See a successful …
=> Rewrite CircleCI to use workflows, containers.

api/document/js/__tests__/fixup-doc.test.ts, api/document/js/__tests__/schema.test.ts, api/document/js/create-editor-state.ts, api/document/js/fixup-doc.ts, api/document/js/keyboard.ts, api/document/js/schema.ts
Previously, we had kept our document schema relatively rigid -- all paragraphs
must have text, all lists: listitems, etc. This doesn't play well with
ProseMirror's internals, which need to be able to delete blocks, text, etc. at
a very fundamental level. The strict schema prevented some of these actions
and would give unexpected results (e.g. replacing a paragraph text with
"undefined") in an effort to maintain a valid document.
This takes a different approach by keeping the schema flexible, but using a
plugin to make a second pass on the modified document and performing fixups
around deleting empty pieces of content.
=> Resolve some issues with text deletion in the editor

api/document/management/commands/import_xml_doc.py, api/document/tests/import_xml_doc_test.py
The current README instructions that instruct a user to use `manage.py import_xml_doc` to import an existing XML doc are a bit developer-unfriendly after #842 because the related policy's `workflow_phase` is still set to `no_doc`, which means that even though the document is stored in the database, it won't be linked-to in the viewer anymore.
This just fixes it so that the related policy's `workflow_phase` is set to `published`, which restores the previous developer experience (and also makes sense semantically).
=> Set workflow phase to 'published' in import_xml_doc command

api/document/js/Api.ts, api/document/js/__tests__/Api.test.ts, api/document/js/__tests__/commands.test.ts, api/document/js/__tests__/create-editor-state.test.ts, api/document/js/akn/main.ts, api/document/js/commands.ts, api/document/js/create-editor-state.ts, api/document/js/keyboard.ts, api/document/js/main.ts, api/document/js/menu.ts, api/document/js/parse-doc.ts, api/document/js/serialize-doc.ts
When I was working on #1003, I realized that I was frequently getting confused about what kind of object was a "Django app document node" vs. what kind of object was a ProseMirror node.  At first I started creating my own typing for the former, until I noticed that it already existed in `serialize-doc.ts`!  So I just moved the related typings from there to `Api.ts`, since that seemed like a more appropriate location for types called `ApiNode` and `ApiContent`.
I also changed `Api` to be parameterized based on whether the caller wants to use it for JSON or AKN+XML, since that alters the return type of the object.
=> Improve API typings

shared-styles/base/_util.scss
ProseMirror's stylesheets alter how whitespace is collapsed by browsers.
Unfortunately, our .clearfix class (based on basscss) assumed whitespace
_would_ be collapsed.
This doesn't affect the viewer, but for the editor:
=> Fix stylesheet for lists.

api/document/js/__tests__/commands.test.ts, api/document/js/__tests__/list-utils.test.ts, api/document/js/commands.ts, api/document/js/keyboard.ts, api/document/js/list-utils.ts, api/document/js/schema.ts, api/document/js/util.ts, api/package-lock.json, api/package.json, api/tslint.yaml
If the cursor's at the end of the text of an existing li (and there are no child nodes, like footnotes), pressing Enter will create a new li immediately following the current, renumber the lis, and place the cursor in the new one.
Renumbering inspects the first li and uses that as a template for all following (meaning we can have arbitrary text in the marker). It'd be a good idea to call the renumbering operating when deleting lis and changing indents, but this doesn't implement those scenarios.
=> Add new li when pressing enter at end of existing li

api/document/js/__tests__/menu.test.ts
If all the buttons
Are clicked in the deep forest
Will anyone know?
Adds a basic check to verify that the ProseMirror editor menu bar has the buttons we think it should have.
=> Add basic tests for ProseMirror menu buttons.

api/document/js/Api.ts
Currently, our `Api` class catches errors and, for ones that aren't actually related to REST API calls, just sets the current status to `An error occurred.` and does nothing else.  If the calling code doesn't re-throw the error, this is actually really unhelpful for developers, because instead of seeing useful information about an error, they just see the uninformative status message and nothing logged to the console.
There's multiple solutions to this problem. This one fixes things by just logging the error to the console if it detects that the error is an unhelpful one.
=> Log unfriendly Api errors in editors.

docker-compose.yml, styleguide/.docker/build_run_styleguide, styleguide/.docker/deps_ok_then
Strangely, the binary symlinks installed in the node environments of `ui` and `api-ui` work okay, but I'm frequently running into https://github.com/docker/for-win/issues/137 for the node environment of `styleguide`, whereby the container's processes think that the symlinks in `node_modules/.bin` are files rather than symlinks.
This works around the bizarre problem by passing a direct path to the relevant scripts.
It also exposes `USE_POLLING` to the `styleguide` container, so that polling works for webpack.
=> Weird Windows fixes.

README.md
I was going through the quick-start earlier today and `sync_agencies` failed because the domain it contacts, `myit-2018.itdashboard.gov`, refused the connection.  I wasn't sure if this meant "game over" and @cmc333333 mentioned that it wasn't even used right now because we've removed agency information from the UI.
We're not removing the functionality entirely because it's likely to come back at some point, but for now it's OK to at least remove the line from the `README.md`.
=> Remove "sync_agencies" from quickstart in README

api/document/js/parse-doc.ts, api/document/js/util.ts, api/package-lock.json, styleguide/package-lock.json, ui/package-lock.json
In production, we were missing a necessary dependency. This was likely due to
trying to generate the ui's package-lock from the shrinkwrap file. This
updates the package-lock files by regenerating them after clearing the
`node_modules` dir.
See [successful deploy](https://circleci.com/gh/18F/omb-eregs/3816).
=> Fixup node 8 deployment by bumping libs

.circleci/config.yml, .gitignore, api/omb_eregs/settings.py, api/ombpdf/management/commands/migrate_documents.py, api/reqs/admin.py, api/reqs/forms.py, api/reqs/models.py, api/reqs/templates/reqs/admin/document_upload.html, api/reqs/tests/admin_tests.py, api/reqs/tests/forms_tests.py, docker-compose.yml, ui/components/policies/policy-view.js
If the policy is marked as having no document (or having a failed import), selecting the "Save and Edit Document" button will redirect to a pdf uploader page. The user can then upload a pdf, which will be processed **in the same thread**. Processing involves:
* Converting the pdf to our internal DocStructs
* Running the document migrations on the result (these'll eventually be part of the import process)
* Creating a "Requirement" for every text node (hacky work-around for our current search)
If the pdf is too large, the request will die and the user will be (understandably) confused. Alas.
This also modifies the UI to stop linking to the requirements listing pages. This uses a percentage of *requirements* that match. Again, this will likely be confusing, but we don't have time to rework …
=> Add very rudimentary PDF import

manifest_prod.yml
Unfortunately, the XML editor wasn't working due to CloudFront stripping the
Accept header. This is fixed in prod, but worth noting somewhere, as it only
affects one environment (and is therefore easy to miss).
=> Add brief notes about CloudFront headers.

api/reqs/admin.py
allows administrator editing file to change the destination of "see original" link for uploaded policies
=> update admin.py to add URI to PolicyAdmin fields
