18F/omb-eregs

.about.yml
Adds in OMB-specific information. I assumed for the purposes of this document that we are going to be implementing an instance of eRegs.
=> Updating .about.yml to remove ATF information

system-security-plan.yml
Adds some initial information about our project's ATO officials. Also marks places we need to generate documents.
=> Update ATO officials and info

.travis.yml, README.md, reqs/management/commands/import_reqs.py
Along the way, tested out the latest data file from OMB and fixed some little issues.
=> Add install instructions

README.md
We can't embed an iframe as Github will strip that.
=> Add demos to README.

.travis.yml
Unfortunately, they require merging this.
=> Testing fixes for autodeploy

package.json, ui/components/app.jsx, ui/server.jsx
Based off http://ericclemmons.com/react-resolver/docs/getting-started/
Two big caveats:
1) I have no affinity for Axios, it's just what was used in that set of docs.
2) This doesn't do the client-side Resolve call
(http://ericclemmons.com/react-resolver/docs/getting-started/ClientRendering.html).
I don't understand what that is or why it'd be helpful.
Also:
0) I don't know what I'm doing.
=> Add veeery rough sketch of isomorphic async calls.

README.md, devops/dev_ui.sh
This should be a wee bit nicer for initial setup and adds some docs for maintenance.
=> Devopsy tweaks and updated docs

omb_eregs/settings.py, reqs/tests/views_tests.py, ui/components/keywords.jsx, ui/components/pagers.jsx, ui/components/requirements.jsx
Suuuper minimal (just a &lt; or &gt;), but this should resolve #69. ~~This also fixes a setup error @micahtaylor ran into when beginning the project.~~ (moved to #71)
=> Add paging to reqs/keywords

README.md, docker-compose.yml, package.json, ui/basic-auth.js, ui/server.jsx
Also includes docs on how to set this up locally.
Not all of #77 as we need to configure the environments, too.
=> Add ability to require basic auth on UI pages.

.babelrc, .eslintrc, .travis.yml, README.md, package.json, ui/__tests__/components/pagers.test.jsx, ui/components/pagers.jsx, webpack.config.js
Using [jest](https://facebook.github.io/jest/) as a test runner and [enzyme](http://airbnb.io/enzyme/) as a react-traversing toolkit. This doesn't do anything with mocks, but I figure it's enough to get us started.
Should resolve #78
=> An initial set of UI tests

reqs/management/commands/import_reqs.py, reqs/tests/import_reqs_tests.py
Often the keywords /
Are inconsistent or wrong /
This mitigates that.
There are still keyword related issues, <https://github.com/18F/omb-eregs/issues/103>, <https://github.com/18F/omb-eregs/issues/104>, and <https://github.com/18F/omb-eregs/issues/105>, but since they require information from OMB I'll address them in separate branches/PRs.
=> 101 keyword inconsistencies

package.json, ui/assets/css/main.scss
This just imports everything -- we might be able to be more modular if that's
desirable.
=> Import basscss styles.

ui/assets/css/_req-filter-ui.scss, ui/assets/css/_requirements.scss, ui/components/app.jsx, ui/components/filter-list.jsx, ui/components/requirements.jsx
Also replaces some of the existing, custom CSS with basscss versions. When the Policy link is clicked, the user's taken to the home page (simplest implementation).
Looks like
Should close #89 and maybe another.
=> Add a nonfunctional tab-based header.

docker-compose.yml, manifest_base.yml, omb_eregs/settings.py, omb_eregs/settings_prod.py, omb_eregs/urls.py, omb_eregs/utils.py, reqs/tests/views_tests.py, reqs/views.py, requirements_dev.in, requirements_dev.txt
To figure the bug out, I added Django Debug Toolbar; kept it in as it'll probably help us debug in the future.
Easiest to review changeset by changeset.
=> Fix a bug around sorting requirements

reqs/management/commands/import_reqs.py, reqs/tests/import_reqs_tests.py
How many problems /
Are due to Excel? The skies /
Refuse to answer.
Since the rows should be sequential, looking for prior rows with requirement IDs ending in `9` and trying to determine the current value seems like a reasonable approach.
=> Try to fix Excel's mangling of decimal values

ui/__tests__/api.test.js, ui/__tests__/components/filter-list.test.jsx, ui/__tests__/components/lookup-search.test.jsx, ui/api.js, ui/components/filter-list.jsx, ui/components/keywords.jsx, ui/components/lookup-search.jsx, ui/components/policies.jsx, ui/components/requirements.jsx, ui/globals.js
This should also create a nicer interface for calling API endpoints.
=> Move API-related functions into a single module.

ui/assets/css/_base.scss, ui/assets/css/_req-filter-ui.scss, ui/assets/css/_requirements.scss, ui/assets/css/_typography.scss, ui/assets/css/main.scss, ui/components/filter-list.jsx, ui/components/navbar.jsx, ui/components/requirements/requirement.jsx, ui/components/requirements/tabs.jsx
I tried translating the text and color definitions in Zeplin into our UI. It looks like this:
Micah, how did I do?
=> Implements font styles per Micah's Zeplin doc

ui/__tests__/components/lookup-search.test.jsx, ui/components/index.jsx, ui/components/lookup-search.jsx, ui/components/search-autocomplete.jsx
We moved around some functions recently and subtly broke autocomplete in the
process. This fixes that issue and adds tests to catch similar issues in the
future.
=> Fix autocomplete bug

ui/assets/css/_base.scss, ui/assets/css/_requirements.scss, ui/components/requirements/by-keyword.jsx, ui/components/requirements/by-policy.jsx, ui/components/requirements/requirement.jsx
Removes an unneeded border around requirements, cleans up spacing, adds a `gray-border` class.
=> Removes duplicate border, grays all borders

.travis.yml
1) Don't let Travis "cleanup" all of the files
2) Specify the space we'll deploy to
=> Try 3 at Travis blue-green deploy.

.travis.yml
This should fix the downtime issues.
=> Bump autopilot version to recently released.

ui/components/requirements/requirement.jsx
You had it right the first time around, @theresaanna !
=> Account for multiple texts with the same key.

README.md
Updates README to better reflect the project.
=> Add better project description to README

.about.yml
Changing things to eRequirements/eReqs may be a little confusing for now, but I think it's worth it for the distinct and descriptive name.
=> Update .about.yml to reflect the current state of things

README.md
I missed one of the system diagrams when adding them to the README.
=> Adds both system diagrams

ui/assets/css/_header.scss, ui/components/navbar.jsx
Adds a "beta" label to the header, in compliance with ATO requirements.
=> Add beta label to header

docker-compose.yml
This feature isn't in Docker stable yet.
=> Avoid using cached volumes.

ui/__tests__/components/requirements/requirements.test.jsx, ui/components/requirements/requirement.jsx
With test. Should resolve #181
=> Make keywords (within a requirement) a link.

ui/README.md
Should close out #170.
@tadhg-ohiggins / @theresaanna feel free to modify
=> README explaining isomorphic philosophy.

manifest_dev.yml, manifest_prod.yml
Also updates dev manifest to match style.
=> Add cio routes.

README.md
=> Update System diagram.

ui/components/index.jsx
=> Fix typo in url for Requirements.

.travis.yml, devops/deploy.sh
When there are changes to a as-of-yet-non-existent "release" branch, run a deploy script for production.
Part of #233
=> Deploy to prod from Travis

.gitignore, ui/components/requirements/container.jsx
Removing policies form sidebar and updating gitignore for listing cache
files.
=> Buh bye policies

reqs/tests/admin_tests.py, requirements.txt, requirements_dev.txt
I think the fix in #287 warrants a hotfix, so I've cherry-picked that commit.
=> Hotfix version of #287

ereqs_admin/tests/admin_tests.py, ereqs_admin/tests/not-a-pdf.txt, reqs/admin.py
The name of a thing /
Should meet our expectations /
Sky should look like sky.
=> Add extension validator for PDF uploads in admin Policy form.

README.md
=> README typo.

reqs/admin.py
I know this is in the backlog, but it was only a one liner, so I went for it.
Should close #310.
Looks like
=> Add some filters to the admin policy screen.

.bandit, .travis.yml, docker-compose.yml, omb_eregs/settings.py, reqs/admin.py, requirements_dev.in, requirements_dev.txt
Changesets should be self-explanatory
=> More security things

ui/__tests__/components/filters/autocompleter.test.js, ui/assets/css/_footer.scss, ui/assets/css/_homepage.scss, ui/assets/css/main.scss, ui/components/app.jsx, ui/components/filters/autocompleter.js, ui/components/filters/search-view.jsx, ui/components/footer.jsx, ui/components/homepage.jsx, ui/components/policies/container.js, ui/components/requirements/container.js, ui/routes.jsx
As I said in the channel, I don't know that my solution for the form is a _good_ one, but it is one. Looking for feedback.
Scope it:
The "about" text is weird. Merriweather renders so much differently in Chrome. Should I do this in a light variant instead?
=> Beginnings of a homepage

ereqs_admin/admin.py, ereqs_admin/templates/admin/auth/user/add_form.html, ereqs_admin/tests/both_user_forms_urls.py, omb_eregs/settings.py, omb_eregs/urls.py, reqs/admin.py, reqs/apps.py, reqs/templates/admin/reqs/policy/change_form.html, reqs/templates/admin/reqs/topic/change_form.html
* Everywhere
* Changing banner header
* Index
* Changed header
* Reqs subapp
* Changing "Reqs" app name
* Policy editing
* Making policy type a radio
* Change heading in table of requirements at bottom of page
* Requirement editing
* Reorder fields a bit
* Topics editing
* Change heading in table at bottom of page
=> Handful of quick tweaks to the admin site

README.md
This also adds a `createinitialrevisions` step to give each of these new
objects an initial version in history.
=> Add agency data step to README.

ui/assets/css/_ie.scss, ui/assets/css/_search-autocomplete.scss, ui/assets/css/main.scss, ui/components/filters/fallback-view.jsx, ui/components/html.jsx, ui/components/navbar.jsx, ui/components/search/search.jsx, ui/ie.js, webpack.config.js
Everything is usable back to IE7. Some aesthetics are a little janky through IE11, but only slightly.
IE7-9 look fairly janky but all features work and there are no reasons someone shouldn't be able to access and use all the content.
IE10 still doesn't have client-side JS happening, but looks a lot better. Form button height is a little off.
IE11 only has form button height issues.
Edge looks great.
It seems like feature detection couldn't get us the level of precision we need on the versions, so I've gone the useragent sniffing route. I realize it's not ideal. Am open to suggestions.
=> Internet Explorer support

ui/components/footer.jsx, ui/components/homepage/view.jsx
=> Text tweaks for launch.

ui/components/footer.jsx, ui/components/privacy-view.jsx, ui/routes.jsx
=> Privacy skeleton

ui/components/homepage/view.jsx, ui/components/html.jsx
We're adding non-IT related policies now; let's adjust the site title and intro text accordingly.
=> tweaks based on increased scope

ui/components/homepage/view.jsx, ui/components/html.jsx
Extends #437 with linting fixes.
=> Tweaks from Matt

ui/components/homepage/view.jsx
=> add a space

devops/integration_tests/conftest.py, reqs/tests/import_reqs_tests.py, reqs/tests/sync_agencies_tests.py, requirements.txt, requirements_dev.txt
=> Bump runtime and dev Python libs

.circleci/config.yml, package.json, setup.cfg
Code Climate's created a new code coverage reporter which allows results from
multiple sources to be submitted. This uses that binary to submit coverage
info from Python and Node.
Resolves #205
=> Add Python code coverage metrics.

ui/components/privacy-view.jsx
The latest versions of eslint catch these issues better, so our builds are
failing.
=> Add spaces to comments.

README.md
Adding the two test commands added recently to the ReadMe.
=> Add the two new test commands to readme

ui/components/errors/four-oh-four-error.js, ui/components/footer.js, ui/components/navbar.js
Ajaxify links
https://github.com/18F/omb-eregs/issues/505
=> Change anchor tag links to use Link component

ui/components/navbar.js, ui/css/_base.scss, ui/css/_header.scss, ui/css/_homepage.scss, ui/css/utils/_landing.scss
- Fixing padding around search bar and reflow sizes.
- Adding case for mobile sized search
- Fixing header reflow with logo/link and header search
- Consistent vertical spacing around header items
- Item alignment
- Adding text content condition to wrap on mobile screens
- Increasing width of search on larger screens
=> Various styles to fix mobile layout and vertical page rhythm

ui/__tests__/components/search/search.test.js, ui/__tests__/pages/policies.test.js, ui/components/policies/policy-view.js, ui/components/search/search.js, ui/pages/policies.js
https://github.com/18F/omb-eregs/issues/543
Reviewed with @micahtaylor to confirm Policy listing items.
=> Update the default search result page and policy listing layout

ui/__tests__/pages/policy.test.js, ui/pages/policy.js
https://github.com/18F/omb-eregs/issues/553
=> Add the reqs req_id as a anchor link into the policy page

api/reqs/tests/views_policies_tests.py, api/reqs/views/policies.py
https://github.com/18F/omb-eregs/issues/551
=> Add policy search through omb_policy_id

README.md
The old youtube link appears to point to an old playlist whose latest video is from April.  This updates the link to the latest playlist that CM gave me.
=> Update youtube link in README.md.

ui/__tests__/util/api/endpoints.test.js, ui/__tests__/util/api/queries.test.js, ui/routes.js, ui/util/api/endpoints.js, ui/util/api/queries.js
https://github.com/18F/omb-eregs/issues/551
=> OMB policy router update for frontend

api/document/tests/views_test.py, api/document/views.py
When serializing a footnote citation, we grab that footnotecitations'
footnote_node (to fetch its identifier). Unfortunately, we hadn't prefetched
any of that data, which meant we were executing an extra query per
footnotecitation.
=> Fix n+1 problem around footnote citations.

ui/components/content-renderers/footnote-citation.js, ui/css/base/_base.scss, ui/css/base/_colors.scss, ui/css/layout/_layout.scss, ui/css/layout/_typography.scss, ui/css/module/_footnotes.scss, ui/css/state/_print.scss
This should also resolve #613.
Key changes:
<hr>
<hr>
<hr>
<hr>
=> Handful of style fixes from #605

ui/__tests__/components/content-renderers/footnote-citation.test.js, ui/__tests__/components/node-renderers/footnote.test.js, ui/__tests__/components/node-renderers/policy.test.js, ui/components/content-renderers/footnote-citation.js, ui/components/node-renderers/footnote.js, ui/components/node-renderers/list-item.js, ui/css/base/_colors.scss, ui/css/layout/_layout.scss, ui/css/layout/_typography.scss, ui/css/module/_footnotes.scss
- https://github.com/18F/omb-eregs/issues/620
- https://github.com/18F/omb-eregs/issues/566
Finishing up styles on the footnotes and remove demo data.
=> Styling footnotes and remove demo data

ui/.eslintignore
=> Make eslint ignore the coverage dir

ui/__tests__/components/content-renderers/footnote-citation.test.js
This adds tests for the functionality introduced in #649.
=> Add tests for footnote citation a11y

ui/components/node-renderers/policy.js, ui/css/layout/_typography.scss, ui/css/main.scss, ui/css/module/_document.scss, ui/css/module/_header.scss, ui/css/module/_landing.scss, ui/css/module/_requirements.scss, ui/css/module/_search-autocomplete.scss, ui/pages/policy.js
Style the document header's `policy` component.
=> Add styles for document header

ui/npm-shrinkwrap.json, ui/package.json
This is a security release. We aren't in danger as we only use trusted input,
but updating won't hurt, either.
=> Bump up moment.

ui/css/module/_footnotes.scss
=> Add styles for footnote triangle

ui/css/base/_base.scss, ui/css/base/_colors.scss, ui/css/layout/_typography.scss, ui/css/module/_button-like.scss, ui/css/module/_external-link.scss, ui/css/module/_footer.scss, ui/css/module/_footnotes.scss, ui/css/module/_header.scss, ui/css/module/_homepage.scss, ui/css/module/_landing.scss, ui/css/module/_loading-indicator.scss, ui/css/module/_req-filter-ui.scss, ui/css/module/_requirements.scss, ui/css/module/_search-autocomplete.scss, ui/css/module/_tables.scss, ui/css/state/_ie.scss, ui/css/state/_print.scss
@rtwell and I worked through this migration of ~50 color variables down to a dozen. As he's already reviewed the color selections, I'm hoping this review can be just a sanity check.
=> Palette reduction

ui/css/module/_footnotes.scss
I had a few ideas for tweaks on #714 but couldn't describe them in words too well, so I broke them into a few commits. Please take a look (reviewing changeset by changeset would be helpful) to see if you agree.
=> Suggestions for #714

api/document/tests/xml_importer/annotations_test.py, api/document/tests/xml_importer/preprocess_test.py, api/document/xml_importer/annotations.py, api/document/xml_importer/preprocess.py
Though it seems likely that we'll be reworking inline requirements, this includes two bug fixes that seemed worth pushing up.
=> Importer for requirements

ui/__tests__/components/document/navigation/nav-link.test.js, ui/components/document/navigation/nav-link.js, ui/npm-shrinkwrap.json, ui/package.json
Smooth scrolling not only looks nicer, but it also hacks around a
react-stickynode bug which was preventing the nav from displaying in some
cases.
Looks like a smoother version of
=> Use smoothscroll within document navigation.

ui/util/api/endpoints.js
=> Disable front-end caching of API in dev.

api/mypy.ini
See the comment in the code diff for an explanation.
=> Disable mypy incremental mode for now

api/package-lock.json
This ensures our dependency versions are identical; see
https://before-you-ship.18f.gov/infrastructure/pinning-dependencies/
Heads up that this includes tslint (see upcoming PR).
=> Add package-lock file.

api/ereqs_admin/templatetags/nav_menu.py
=> Lazily create menu archetype.

api/document/models.py, api/document/views.py
This minor refactoring moves our `document.views.optimize()` function into a custom `QuerySet` subclass, calling it `prefetch_annotations()` (since that is what it appears to do).
The primary rationale behind this is that I was looking at the steps behind adding a new annotation subclass for #901 and noticed that it would involve modifying `document.views.optimize()`.  This seemed like a step that could be easily forgotten, and I thought it might be easier to remember to do if it were in `document.models`, which is the site of other annotation-related code. Aside from that, though, a custom `QuerySet` method just seemed like the right kind of place for such logic.
=> Factor out a DocNodeQuerySet class

api/document/models.py, api/document/serializers/doc_cursor.py, api/document/tests/serializers/doc_cursor_test.py
=> Validate type_emblem

api/document/templates/document/editor_akn.html, api/package-lock.json
Also fixes an issue with the typescript package lock file.
=> Add *very* rough XML instructions
